; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:     --disable-block-placement < %s \
; RUN:   | FileCheck -check-prefixes=ALL %s
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:     --disable-block-placement \
; RUN:     -mattr=+xkeysomnobgeu < %s \
; RUN:   | FileCheck -check-prefixes=NOBGEU %s

define i32 @f(i32 %a, i32 %b) {
; ALL-LABEL: f:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    bgeu a0, a1, .LBB0_2
; ALL-NEXT:  # %bb.1:
; ALL-NEXT:    addi a0, zero, 11
; ALL-NEXT:    jalr zero, 0(ra)
; ALL-NEXT:  .LBB0_2: # %entry
; ALL-NEXT:    addi a0, zero, 7
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOBGEU-LABEL: f:
; NOBGEU:       # %bb.0: # %entry
; NOBGEU-NEXT:    bltu a0, a1, .LBB0_1
; NOBGEU-NEXT:    jal zero, .LBB0_2
; NOBGEU-NEXT:  .LBB0_1:
; NOBGEU-NEXT:    addi a0, zero, 11
; NOBGEU-NEXT:    jalr zero, 0(ra)
; NOBGEU-NEXT:  .LBB0_2: # %entry
; NOBGEU-NEXT:    addi a0, zero, 7
; NOBGEU-NEXT:    jalr zero, 0(ra)

entry:
  %cmp.not = icmp ult i32 %a, %b
  %cond = select i1 %cmp.not, i32 11, i32 7
  ret i32 %cond
}
