; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs < %s | FileCheck -check-prefixes=ALL %s
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:   -mattr=+xkeysomnolb < %s | FileCheck -check-prefixes=NOLB %s
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:   -mattr=+xkeysomnolbu < %s | FileCheck -check-prefixes=NOLBU %s
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:   -mattr=+xkeysomnolh < %s | FileCheck -check-prefixes=NOLH %s
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:   -mattr=+xkeysomnolhu < %s | FileCheck -check-prefixes=NOLHU %s
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:   -mattr=+xkeysomnolb \
; RUN:   -mattr=+xkeysomnolbu \
; RUN:   -mattr=+xkeysomnolh \
; RUN:   -mattr=+xkeysomnolhu < %s | FileCheck -check-prefixes=NOL %s

; force_spill.ll — create many independent volatile values used after a call
; Each @vN is an externally defined volatile source so loads can't be folded away.

@v0  = external global i8
@v1  = external global i16
@v2  = external global i8
@v3  = external global i16
@v4  = external global i8
@v5  = external global i16
@v6  = external global i8
@v7  = external global i16
@v8  = external global i8
@v9  = external global i16
@v10 = external global i8
@v11 = external global i16
@v12 = external global i8
@v13 = external global i16
@v14 = external global i8
@v15 = external global i16
@v16 = external global i8
@v17 = external global i16
@v18 = external global i8
@v19 = external global i16

declare void @clobber()

define i16 @force_spill(i16 %x) nounwind {
; ALL-LABEL: force_spill:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    addi sp, sp, -96
; ALL-NEXT:    sw ra, 92(sp) # 4-byte Folded Spill
; ALL-NEXT:    sw s0, 88(sp) # 4-byte Folded Spill
; ALL-NEXT:    sw s1, 84(sp) # 4-byte Folded Spill
; ALL-NEXT:    sw s2, 80(sp) # 4-byte Folded Spill
; ALL-NEXT:    sw s3, 76(sp) # 4-byte Folded Spill
; ALL-NEXT:    sw s4, 72(sp) # 4-byte Folded Spill
; ALL-NEXT:    sw s5, 68(sp) # 4-byte Folded Spill
; ALL-NEXT:    sw s6, 64(sp) # 4-byte Folded Spill
; ALL-NEXT:    sw s7, 60(sp) # 4-byte Folded Spill
; ALL-NEXT:    sw s8, 56(sp) # 4-byte Folded Spill
; ALL-NEXT:    sw s9, 52(sp) # 4-byte Folded Spill
; ALL-NEXT:    sw s10, 48(sp) # 4-byte Folded Spill
; ALL-NEXT:    sw s11, 44(sp) # 4-byte Folded Spill
; ALL-NEXT:    lui s0, %hi(v0)
; ALL-NEXT:    lui s1, %hi(v1)
; ALL-NEXT:    lui s3, %hi(v2)
; ALL-NEXT:    lui s2, %hi(v3)
; ALL-NEXT:    lui a4, %hi(v4)
; ALL-NEXT:    lui a5, %hi(v5)
; ALL-NEXT:    lui a6, %hi(v6)
; ALL-NEXT:    lui a7, %hi(v7)
; ALL-NEXT:    lui t0, %hi(v8)
; ALL-NEXT:    lui t1, %hi(v9)
; ALL-NEXT:    lui t2, %hi(v10)
; ALL-NEXT:    lui t3, %hi(v11)
; ALL-NEXT:    lui t4, %hi(v12)
; ALL-NEXT:    lui t5, %hi(v13)
; ALL-NEXT:    lui t6, %hi(v14)
; ALL-NEXT:    lui ra, %hi(v15)
; ALL-NEXT:    lui a0, %hi(v16)
; ALL-NEXT:    lui a1, %hi(v17)
; ALL-NEXT:    lui a2, %hi(v18)
; ALL-NEXT:    lui a3, %hi(v19)
; ALL-NEXT:    lh s0, %lo(v0)(s0)
; ALL-NEXT:    sw s0, 40(sp) # 4-byte Folded Spill
; ALL-NEXT:    lh s0, %lo(v1)(s1)
; ALL-NEXT:    sw s0, 36(sp) # 4-byte Folded Spill
; ALL-NEXT:    lh s0, %lo(v2)(s3)
; ALL-NEXT:    sw s0, 32(sp) # 4-byte Folded Spill
; ALL-NEXT:    lh s0, %lo(v3)(s2)
; ALL-NEXT:    sw s0, 28(sp) # 4-byte Folded Spill
; ALL-NEXT:    lh a4, %lo(v4)(a4)
; ALL-NEXT:    sw a4, 24(sp) # 4-byte Folded Spill
; ALL-NEXT:    lh a4, %lo(v5)(a5)
; ALL-NEXT:    sw a4, 20(sp) # 4-byte Folded Spill
; ALL-NEXT:    lh a4, %lo(v6)(a6)
; ALL-NEXT:    sw a4, 16(sp) # 4-byte Folded Spill
; ALL-NEXT:    lh a4, %lo(v7)(a7)
; ALL-NEXT:    sw a4, 12(sp) # 4-byte Folded Spill
; ALL-NEXT:    lh s1, %lo(v8)(t0)
; ALL-NEXT:    lh s6, %lo(v9)(t1)
; ALL-NEXT:    lh s7, %lo(v10)(t2)
; ALL-NEXT:    lh s8, %lo(v11)(t3)
; ALL-NEXT:    lh s9, %lo(v12)(t4)
; ALL-NEXT:    lh s3, %lo(v13)(t5)
; ALL-NEXT:    lh s4, %lo(v14)(t6)
; ALL-NEXT:    lh s5, %lo(v15)(ra)
; ALL-NEXT:    lh s10, %lo(v16)(a0)
; ALL-NEXT:    lh s2, %lo(v17)(a1)
; ALL-NEXT:    lh s11, %lo(v18)(a2)
; ALL-NEXT:    lh s0, %lo(v19)(a3)
; ALL-NEXT:    call clobber
; ALL-NEXT:    lw a0, 40(sp) # 4-byte Folded Reload
; ALL-NEXT:    lw a1, 36(sp) # 4-byte Folded Reload
; ALL-NEXT:    add a0, a0, a1
; ALL-NEXT:    lw a1, 32(sp) # 4-byte Folded Reload
; ALL-NEXT:    lw a2, 28(sp) # 4-byte Folded Reload
; ALL-NEXT:    add a1, a1, a2
; ALL-NEXT:    lw a2, 24(sp) # 4-byte Folded Reload
; ALL-NEXT:    lw a3, 20(sp) # 4-byte Folded Reload
; ALL-NEXT:    add a2, a2, a3
; ALL-NEXT:    lw a3, 16(sp) # 4-byte Folded Reload
; ALL-NEXT:    lw a4, 12(sp) # 4-byte Folded Reload
; ALL-NEXT:    add a3, a3, a4
; ALL-NEXT:    add s1, s1, s6
; ALL-NEXT:    add s7, s7, s8
; ALL-NEXT:    add s3, s9, s3
; ALL-NEXT:    add s4, s4, s5
; ALL-NEXT:    add s2, s10, s2
; ALL-NEXT:    add s0, s11, s0
; ALL-NEXT:    add a0, a0, a1
; ALL-NEXT:    add a2, a2, a3
; ALL-NEXT:    add s1, s1, s7
; ALL-NEXT:    add s3, s3, s4
; ALL-NEXT:    add s0, s2, s0
; ALL-NEXT:    add a0, a0, a2
; ALL-NEXT:    add s1, s1, s3
; ALL-NEXT:    add a0, a0, s1
; ALL-NEXT:    add a0, a0, s0
; ALL-NEXT:    lw ra, 92(sp) # 4-byte Folded Reload
; ALL-NEXT:    lw s0, 88(sp) # 4-byte Folded Reload
; ALL-NEXT:    lw s1, 84(sp) # 4-byte Folded Reload
; ALL-NEXT:    lw s2, 80(sp) # 4-byte Folded Reload
; ALL-NEXT:    lw s3, 76(sp) # 4-byte Folded Reload
; ALL-NEXT:    lw s4, 72(sp) # 4-byte Folded Reload
; ALL-NEXT:    lw s5, 68(sp) # 4-byte Folded Reload
; ALL-NEXT:    lw s6, 64(sp) # 4-byte Folded Reload
; ALL-NEXT:    lw s7, 60(sp) # 4-byte Folded Reload
; ALL-NEXT:    lw s8, 56(sp) # 4-byte Folded Reload
; ALL-NEXT:    lw s9, 52(sp) # 4-byte Folded Reload
; ALL-NEXT:    lw s10, 48(sp) # 4-byte Folded Reload
; ALL-NEXT:    lw s11, 44(sp) # 4-byte Folded Reload
; ALL-NEXT:    addi sp, sp, 96
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOLB-LABEL: force_spill:
; NOLB:       # %bb.0: # %entry
; NOLB-NEXT:    addi sp, sp, -96
; NOLB-NEXT:    sw ra, 92(sp) # 4-byte Folded Spill
; NOLB-NEXT:    sw s0, 88(sp) # 4-byte Folded Spill
; NOLB-NEXT:    sw s1, 84(sp) # 4-byte Folded Spill
; NOLB-NEXT:    sw s2, 80(sp) # 4-byte Folded Spill
; NOLB-NEXT:    sw s3, 76(sp) # 4-byte Folded Spill
; NOLB-NEXT:    sw s4, 72(sp) # 4-byte Folded Spill
; NOLB-NEXT:    sw s5, 68(sp) # 4-byte Folded Spill
; NOLB-NEXT:    sw s6, 64(sp) # 4-byte Folded Spill
; NOLB-NEXT:    sw s7, 60(sp) # 4-byte Folded Spill
; NOLB-NEXT:    sw s8, 56(sp) # 4-byte Folded Spill
; NOLB-NEXT:    sw s9, 52(sp) # 4-byte Folded Spill
; NOLB-NEXT:    sw s10, 48(sp) # 4-byte Folded Spill
; NOLB-NEXT:    sw s11, 44(sp) # 4-byte Folded Spill
; NOLB-NEXT:    lui s0, %hi(v0)
; NOLB-NEXT:    lui s1, %hi(v1)
; NOLB-NEXT:    lui s3, %hi(v2)
; NOLB-NEXT:    lui s2, %hi(v3)
; NOLB-NEXT:    lui a4, %hi(v4)
; NOLB-NEXT:    lui a5, %hi(v5)
; NOLB-NEXT:    lui a6, %hi(v6)
; NOLB-NEXT:    lui a7, %hi(v7)
; NOLB-NEXT:    lui t0, %hi(v8)
; NOLB-NEXT:    lui t1, %hi(v9)
; NOLB-NEXT:    lui t2, %hi(v10)
; NOLB-NEXT:    lui t3, %hi(v11)
; NOLB-NEXT:    lui t4, %hi(v12)
; NOLB-NEXT:    lui t5, %hi(v13)
; NOLB-NEXT:    lui t6, %hi(v14)
; NOLB-NEXT:    lui ra, %hi(v15)
; NOLB-NEXT:    lui a0, %hi(v16)
; NOLB-NEXT:    lui a1, %hi(v17)
; NOLB-NEXT:    lui a2, %hi(v18)
; NOLB-NEXT:    lui a3, %hi(v19)
; NOLB-NEXT:    lh s0, %lo(v0)(s0)
; NOLB-NEXT:    sw s0, 40(sp) # 4-byte Folded Spill
; NOLB-NEXT:    lh s0, %lo(v1)(s1)
; NOLB-NEXT:    sw s0, 36(sp) # 4-byte Folded Spill
; NOLB-NEXT:    lh s0, %lo(v2)(s3)
; NOLB-NEXT:    sw s0, 32(sp) # 4-byte Folded Spill
; NOLB-NEXT:    lh s0, %lo(v3)(s2)
; NOLB-NEXT:    sw s0, 28(sp) # 4-byte Folded Spill
; NOLB-NEXT:    lh a4, %lo(v4)(a4)
; NOLB-NEXT:    sw a4, 24(sp) # 4-byte Folded Spill
; NOLB-NEXT:    lh a4, %lo(v5)(a5)
; NOLB-NEXT:    sw a4, 20(sp) # 4-byte Folded Spill
; NOLB-NEXT:    lh a4, %lo(v6)(a6)
; NOLB-NEXT:    sw a4, 16(sp) # 4-byte Folded Spill
; NOLB-NEXT:    lh a4, %lo(v7)(a7)
; NOLB-NEXT:    sw a4, 12(sp) # 4-byte Folded Spill
; NOLB-NEXT:    lh s1, %lo(v8)(t0)
; NOLB-NEXT:    lh s6, %lo(v9)(t1)
; NOLB-NEXT:    lh s7, %lo(v10)(t2)
; NOLB-NEXT:    lh s8, %lo(v11)(t3)
; NOLB-NEXT:    lh s9, %lo(v12)(t4)
; NOLB-NEXT:    lh s3, %lo(v13)(t5)
; NOLB-NEXT:    lh s4, %lo(v14)(t6)
; NOLB-NEXT:    lh s5, %lo(v15)(ra)
; NOLB-NEXT:    lh s10, %lo(v16)(a0)
; NOLB-NEXT:    lh s2, %lo(v17)(a1)
; NOLB-NEXT:    lh s11, %lo(v18)(a2)
; NOLB-NEXT:    lh s0, %lo(v19)(a3)
; NOLB-NEXT:    call clobber
; NOLB-NEXT:    lw a0, 40(sp) # 4-byte Folded Reload
; NOLB-NEXT:    lw a1, 36(sp) # 4-byte Folded Reload
; NOLB-NEXT:    add a0, a0, a1
; NOLB-NEXT:    lw a1, 32(sp) # 4-byte Folded Reload
; NOLB-NEXT:    lw a2, 28(sp) # 4-byte Folded Reload
; NOLB-NEXT:    add a1, a1, a2
; NOLB-NEXT:    lw a2, 24(sp) # 4-byte Folded Reload
; NOLB-NEXT:    lw a3, 20(sp) # 4-byte Folded Reload
; NOLB-NEXT:    add a2, a2, a3
; NOLB-NEXT:    lw a3, 16(sp) # 4-byte Folded Reload
; NOLB-NEXT:    lw a4, 12(sp) # 4-byte Folded Reload
; NOLB-NEXT:    add a3, a3, a4
; NOLB-NEXT:    add s1, s1, s6
; NOLB-NEXT:    add s7, s7, s8
; NOLB-NEXT:    add s3, s9, s3
; NOLB-NEXT:    add s4, s4, s5
; NOLB-NEXT:    add s2, s10, s2
; NOLB-NEXT:    add s0, s11, s0
; NOLB-NEXT:    add a0, a0, a1
; NOLB-NEXT:    add a2, a2, a3
; NOLB-NEXT:    add s1, s1, s7
; NOLB-NEXT:    add s3, s3, s4
; NOLB-NEXT:    add s0, s2, s0
; NOLB-NEXT:    add a0, a0, a2
; NOLB-NEXT:    add s1, s1, s3
; NOLB-NEXT:    add a0, a0, s1
; NOLB-NEXT:    add a0, a0, s0
; NOLB-NEXT:    lw ra, 92(sp) # 4-byte Folded Reload
; NOLB-NEXT:    lw s0, 88(sp) # 4-byte Folded Reload
; NOLB-NEXT:    lw s1, 84(sp) # 4-byte Folded Reload
; NOLB-NEXT:    lw s2, 80(sp) # 4-byte Folded Reload
; NOLB-NEXT:    lw s3, 76(sp) # 4-byte Folded Reload
; NOLB-NEXT:    lw s4, 72(sp) # 4-byte Folded Reload
; NOLB-NEXT:    lw s5, 68(sp) # 4-byte Folded Reload
; NOLB-NEXT:    lw s6, 64(sp) # 4-byte Folded Reload
; NOLB-NEXT:    lw s7, 60(sp) # 4-byte Folded Reload
; NOLB-NEXT:    lw s8, 56(sp) # 4-byte Folded Reload
; NOLB-NEXT:    lw s9, 52(sp) # 4-byte Folded Reload
; NOLB-NEXT:    lw s10, 48(sp) # 4-byte Folded Reload
; NOLB-NEXT:    lw s11, 44(sp) # 4-byte Folded Reload
; NOLB-NEXT:    addi sp, sp, 96
; NOLB-NEXT:    jalr zero, 0(ra)
;
; NOLBU-LABEL: force_spill:
; NOLBU:       # %bb.0: # %entry
; NOLBU-NEXT:    addi sp, sp, -96
; NOLBU-NEXT:    sw ra, 92(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    sw s0, 88(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    sw s1, 84(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    sw s2, 80(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    sw s3, 76(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    sw s4, 72(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    sw s5, 68(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    sw s6, 64(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    sw s7, 60(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    sw s8, 56(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    sw s9, 52(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    sw s10, 48(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    sw s11, 44(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    lui s0, %hi(v0)
; NOLBU-NEXT:    lui s1, %hi(v1)
; NOLBU-NEXT:    lui s3, %hi(v2)
; NOLBU-NEXT:    lui s2, %hi(v3)
; NOLBU-NEXT:    lui a4, %hi(v4)
; NOLBU-NEXT:    lui a5, %hi(v5)
; NOLBU-NEXT:    lui a6, %hi(v6)
; NOLBU-NEXT:    lui a7, %hi(v7)
; NOLBU-NEXT:    lui t0, %hi(v8)
; NOLBU-NEXT:    lui t1, %hi(v9)
; NOLBU-NEXT:    lui t2, %hi(v10)
; NOLBU-NEXT:    lui t3, %hi(v11)
; NOLBU-NEXT:    lui t4, %hi(v12)
; NOLBU-NEXT:    lui t5, %hi(v13)
; NOLBU-NEXT:    lui t6, %hi(v14)
; NOLBU-NEXT:    lui ra, %hi(v15)
; NOLBU-NEXT:    lui a0, %hi(v16)
; NOLBU-NEXT:    lui a1, %hi(v17)
; NOLBU-NEXT:    lui a2, %hi(v18)
; NOLBU-NEXT:    lui a3, %hi(v19)
; NOLBU-NEXT:    lh s0, %lo(v0)(s0)
; NOLBU-NEXT:    sw s0, 40(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    lh s0, %lo(v1)(s1)
; NOLBU-NEXT:    sw s0, 36(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    lh s0, %lo(v2)(s3)
; NOLBU-NEXT:    sw s0, 32(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    lh s0, %lo(v3)(s2)
; NOLBU-NEXT:    sw s0, 28(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    lh a4, %lo(v4)(a4)
; NOLBU-NEXT:    sw a4, 24(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    lh a4, %lo(v5)(a5)
; NOLBU-NEXT:    sw a4, 20(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    lh a4, %lo(v6)(a6)
; NOLBU-NEXT:    sw a4, 16(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    lh a4, %lo(v7)(a7)
; NOLBU-NEXT:    sw a4, 12(sp) # 4-byte Folded Spill
; NOLBU-NEXT:    lh s1, %lo(v8)(t0)
; NOLBU-NEXT:    lh s6, %lo(v9)(t1)
; NOLBU-NEXT:    lh s7, %lo(v10)(t2)
; NOLBU-NEXT:    lh s8, %lo(v11)(t3)
; NOLBU-NEXT:    lh s9, %lo(v12)(t4)
; NOLBU-NEXT:    lh s3, %lo(v13)(t5)
; NOLBU-NEXT:    lh s4, %lo(v14)(t6)
; NOLBU-NEXT:    lh s5, %lo(v15)(ra)
; NOLBU-NEXT:    lh s10, %lo(v16)(a0)
; NOLBU-NEXT:    lh s2, %lo(v17)(a1)
; NOLBU-NEXT:    lh s11, %lo(v18)(a2)
; NOLBU-NEXT:    lh s0, %lo(v19)(a3)
; NOLBU-NEXT:    call clobber
; NOLBU-NEXT:    lw a0, 40(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    lw a1, 36(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    add a0, a0, a1
; NOLBU-NEXT:    lw a1, 32(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    lw a2, 28(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    add a1, a1, a2
; NOLBU-NEXT:    lw a2, 24(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    lw a3, 20(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    add a2, a2, a3
; NOLBU-NEXT:    lw a3, 16(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    lw a4, 12(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    add a3, a3, a4
; NOLBU-NEXT:    add s1, s1, s6
; NOLBU-NEXT:    add s7, s7, s8
; NOLBU-NEXT:    add s3, s9, s3
; NOLBU-NEXT:    add s4, s4, s5
; NOLBU-NEXT:    add s2, s10, s2
; NOLBU-NEXT:    add s0, s11, s0
; NOLBU-NEXT:    add a0, a0, a1
; NOLBU-NEXT:    add a2, a2, a3
; NOLBU-NEXT:    add s1, s1, s7
; NOLBU-NEXT:    add s3, s3, s4
; NOLBU-NEXT:    add s0, s2, s0
; NOLBU-NEXT:    add a0, a0, a2
; NOLBU-NEXT:    add s1, s1, s3
; NOLBU-NEXT:    add a0, a0, s1
; NOLBU-NEXT:    add a0, a0, s0
; NOLBU-NEXT:    lw ra, 92(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    lw s0, 88(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    lw s1, 84(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    lw s2, 80(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    lw s3, 76(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    lw s4, 72(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    lw s5, 68(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    lw s6, 64(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    lw s7, 60(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    lw s8, 56(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    lw s9, 52(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    lw s10, 48(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    lw s11, 44(sp) # 4-byte Folded Reload
; NOLBU-NEXT:    addi sp, sp, 96
; NOLBU-NEXT:    jalr zero, 0(ra)
;
; NOLH-LABEL: force_spill:
; NOLH:       # %bb.0: # %entry
; NOLH-NEXT:    addi sp, sp, -96
; NOLH-NEXT:    sw ra, 92(sp) # 4-byte Folded Spill
; NOLH-NEXT:    sw s0, 88(sp) # 4-byte Folded Spill
; NOLH-NEXT:    sw s1, 84(sp) # 4-byte Folded Spill
; NOLH-NEXT:    sw s2, 80(sp) # 4-byte Folded Spill
; NOLH-NEXT:    sw s3, 76(sp) # 4-byte Folded Spill
; NOLH-NEXT:    sw s4, 72(sp) # 4-byte Folded Spill
; NOLH-NEXT:    sw s5, 68(sp) # 4-byte Folded Spill
; NOLH-NEXT:    sw s6, 64(sp) # 4-byte Folded Spill
; NOLH-NEXT:    sw s7, 60(sp) # 4-byte Folded Spill
; NOLH-NEXT:    sw s8, 56(sp) # 4-byte Folded Spill
; NOLH-NEXT:    sw s9, 52(sp) # 4-byte Folded Spill
; NOLH-NEXT:    sw s10, 48(sp) # 4-byte Folded Spill
; NOLH-NEXT:    sw s11, 44(sp) # 4-byte Folded Spill
; NOLH-NEXT:    lui a0, %hi(v0)
; NOLH-NEXT:    lui a1, %hi(v1)
; NOLH-NEXT:    lui a2, %hi(v2)
; NOLH-NEXT:    lui a3, %hi(v3)
; NOLH-NEXT:    lui a4, %hi(v4)
; NOLH-NEXT:    lui a5, %hi(v5)
; NOLH-NEXT:    lui a6, %hi(v6)
; NOLH-NEXT:    lui a7, %hi(v7)
; NOLH-NEXT:    lui t0, %hi(v8)
; NOLH-NEXT:    lui t1, %hi(v9)
; NOLH-NEXT:    lui t2, %hi(v10)
; NOLH-NEXT:    lui t3, %hi(v11)
; NOLH-NEXT:    lui t4, %hi(v12)
; NOLH-NEXT:    lui t5, %hi(v13)
; NOLH-NEXT:    lui s0, %hi(v14)
; NOLH-NEXT:    lui s2, %hi(v15)
; NOLH-NEXT:    lui s4, %hi(v16)
; NOLH-NEXT:    lui s5, %hi(v17)
; NOLH-NEXT:    lui s6, %hi(v18)
; NOLH-NEXT:    lui s7, %hi(v19)
; NOLH-NEXT:    addi s8, a0, %lo(v0)
; NOLH-NEXT:    addi a1, a1, %lo(v1)
; NOLH-NEXT:    addi s9, a2, %lo(v2)
; NOLH-NEXT:    addi s10, a3, %lo(v3)
; NOLH-NEXT:    addi s11, a4, %lo(v4)
; NOLH-NEXT:    addi ra, a5, %lo(v5)
; NOLH-NEXT:    addi a3, a6, %lo(v6)
; NOLH-NEXT:    addi a5, a7, %lo(v7)
; NOLH-NEXT:    addi a7, t0, %lo(v8)
; NOLH-NEXT:    addi t1, t1, %lo(v9)
; NOLH-NEXT:    addi s3, t2, %lo(v10)
; NOLH-NEXT:    addi s1, t3, %lo(v11)
; NOLH-NEXT:    addi t6, t4, %lo(v12)
; NOLH-NEXT:    addi t4, t5, %lo(v13)
; NOLH-NEXT:    addi t2, s0, %lo(v14)
; NOLH-NEXT:    addi t0, s2, %lo(v15)
; NOLH-NEXT:    addi a6, s4, %lo(v16)
; NOLH-NEXT:    addi a4, s5, %lo(v17)
; NOLH-NEXT:    addi a2, s6, %lo(v18)
; NOLH-NEXT:    addi a0, s7, %lo(v19)
; NOLH-NEXT:    andi t3, s8, -4
; NOLH-NEXT:    andi t5, a1, -4
; NOLH-NEXT:    sub s0, s8, t3
; NOLH-NEXT:    lw t3, 0(t3)
; NOLH-NEXT:    sub s2, a1, t5
; NOLH-NEXT:    lw t5, 0(t5)
; NOLH-NEXT:    slli s0, s0, 3
; NOLH-NEXT:    srl a1, t3, s0
; NOLH-NEXT:    andi t3, s9, -4
; NOLH-NEXT:    slli s2, s2, 3
; NOLH-NEXT:    srl s5, t5, s2
; NOLH-NEXT:    andi t5, s10, -4
; NOLH-NEXT:    sub s0, s9, t3
; NOLH-NEXT:    lw t3, 0(t3)
; NOLH-NEXT:    sub s2, s10, t5
; NOLH-NEXT:    lw t5, 0(t5)
; NOLH-NEXT:    slli s0, s0, 3
; NOLH-NEXT:    srl s6, t3, s0
; NOLH-NEXT:    andi t3, s11, -4
; NOLH-NEXT:    slli s2, s2, 3
; NOLH-NEXT:    srl s7, t5, s2
; NOLH-NEXT:    andi t5, ra, -4
; NOLH-NEXT:    sub s0, s11, t3
; NOLH-NEXT:    lw t3, 0(t3)
; NOLH-NEXT:    sub s2, ra, t5
; NOLH-NEXT:    lw t5, 0(t5)
; NOLH-NEXT:    slli s0, s0, 3
; NOLH-NEXT:    srl s8, t3, s0
; NOLH-NEXT:    andi s0, a3, -4
; NOLH-NEXT:    slli s2, s2, 3
; NOLH-NEXT:    srl t3, t5, s2
; NOLH-NEXT:    andi t5, a5, -4
; NOLH-NEXT:    sub a3, a3, s0
; NOLH-NEXT:    lw s0, 0(s0)
; NOLH-NEXT:    sub a5, a5, t5
; NOLH-NEXT:    lw s2, 0(t5)
; NOLH-NEXT:    slli a3, a3, 3
; NOLH-NEXT:    srl t5, s0, a3
; NOLH-NEXT:    andi a3, a7, -4
; NOLH-NEXT:    slli a5, a5, 3
; NOLH-NEXT:    srl s0, s2, a5
; NOLH-NEXT:    andi a5, t1, -4
; NOLH-NEXT:    sub a7, a7, a3
; NOLH-NEXT:    lw a3, 0(a3)
; NOLH-NEXT:    sub t1, t1, a5
; NOLH-NEXT:    lw a5, 0(a5)
; NOLH-NEXT:    slli a7, a7, 3
; NOLH-NEXT:    srl s2, a3, a7
; NOLH-NEXT:    andi a3, s3, -4
; NOLH-NEXT:    slli t1, t1, 3
; NOLH-NEXT:    srl s4, a5, t1
; NOLH-NEXT:    andi a5, s1, -4
; NOLH-NEXT:    sub a7, s3, a3
; NOLH-NEXT:    lw a3, 0(a3)
; NOLH-NEXT:    sub s1, s1, a5
; NOLH-NEXT:    lw a5, 0(a5)
; NOLH-NEXT:    slli a7, a7, 3
; NOLH-NEXT:    srl a3, a3, a7
; NOLH-NEXT:    andi a7, t6, -4
; NOLH-NEXT:    slli s1, s1, 3
; NOLH-NEXT:    srl a5, a5, s1
; NOLH-NEXT:    andi t1, t4, -4
; NOLH-NEXT:    sub t6, t6, a7
; NOLH-NEXT:    lw a7, 0(a7)
; NOLH-NEXT:    sub t4, t4, t1
; NOLH-NEXT:    lw t1, 0(t1)
; NOLH-NEXT:    slli t6, t6, 3
; NOLH-NEXT:    srl a7, a7, t6
; NOLH-NEXT:    andi t6, t2, -4
; NOLH-NEXT:    slli t4, t4, 3
; NOLH-NEXT:    srl t1, t1, t4
; NOLH-NEXT:    andi t4, t0, -4
; NOLH-NEXT:    sub t2, t2, t6
; NOLH-NEXT:    lw t6, 0(t6)
; NOLH-NEXT:    sub t0, t0, t4
; NOLH-NEXT:    lw t4, 0(t4)
; NOLH-NEXT:    slli t2, t2, 3
; NOLH-NEXT:    srl t2, t6, t2
; NOLH-NEXT:    andi t6, a6, -4
; NOLH-NEXT:    slli t0, t0, 3
; NOLH-NEXT:    srl t0, t4, t0
; NOLH-NEXT:    andi t4, a4, -4
; NOLH-NEXT:    sub a6, a6, t6
; NOLH-NEXT:    lw t6, 0(t6)
; NOLH-NEXT:    sub a4, a4, t4
; NOLH-NEXT:    lw t4, 0(t4)
; NOLH-NEXT:    slli a6, a6, 3
; NOLH-NEXT:    srl a6, t6, a6
; NOLH-NEXT:    andi t6, a2, -4
; NOLH-NEXT:    slli a4, a4, 3
; NOLH-NEXT:    srl a4, t4, a4
; NOLH-NEXT:    andi t4, a0, -4
; NOLH-NEXT:    sub a2, a2, t6
; NOLH-NEXT:    lw t6, 0(t6)
; NOLH-NEXT:    sub a0, a0, t4
; NOLH-NEXT:    lw t4, 0(t4)
; NOLH-NEXT:    slli a2, a2, 3
; NOLH-NEXT:    slli a0, a0, 3
; NOLH-NEXT:    srl a2, t6, a2
; NOLH-NEXT:    srl a0, t4, a0
; NOLH-NEXT:    slli a1, a1, 16
; NOLH-NEXT:    slli s5, s5, 16
; NOLH-NEXT:    slli s6, s6, 16
; NOLH-NEXT:    slli s7, s7, 16
; NOLH-NEXT:    slli s8, s8, 16
; NOLH-NEXT:    slli t3, t3, 16
; NOLH-NEXT:    slli t5, t5, 16
; NOLH-NEXT:    slli s0, s0, 16
; NOLH-NEXT:    slli s2, s2, 16
; NOLH-NEXT:    slli s4, s4, 16
; NOLH-NEXT:    slli a3, a3, 16
; NOLH-NEXT:    slli a5, a5, 16
; NOLH-NEXT:    slli a7, a7, 16
; NOLH-NEXT:    slli t1, t1, 16
; NOLH-NEXT:    slli t2, t2, 16
; NOLH-NEXT:    slli t0, t0, 16
; NOLH-NEXT:    slli a6, a6, 16
; NOLH-NEXT:    slli a4, a4, 16
; NOLH-NEXT:    slli a2, a2, 16
; NOLH-NEXT:    slli a0, a0, 16
; NOLH-NEXT:    srai a1, a1, 16
; NOLH-NEXT:    sw a1, 40(sp) # 4-byte Folded Spill
; NOLH-NEXT:    srai a1, s5, 16
; NOLH-NEXT:    sw a1, 36(sp) # 4-byte Folded Spill
; NOLH-NEXT:    srai a1, s6, 16
; NOLH-NEXT:    sw a1, 32(sp) # 4-byte Folded Spill
; NOLH-NEXT:    srai a1, s7, 16
; NOLH-NEXT:    sw a1, 28(sp) # 4-byte Folded Spill
; NOLH-NEXT:    srai a1, s8, 16
; NOLH-NEXT:    sw a1, 24(sp) # 4-byte Folded Spill
; NOLH-NEXT:    srai a1, t3, 16
; NOLH-NEXT:    sw a1, 20(sp) # 4-byte Folded Spill
; NOLH-NEXT:    srai a1, t5, 16
; NOLH-NEXT:    sw a1, 16(sp) # 4-byte Folded Spill
; NOLH-NEXT:    srai s0, s0, 16
; NOLH-NEXT:    sw s0, 12(sp) # 4-byte Folded Spill
; NOLH-NEXT:    srai s2, s2, 16
; NOLH-NEXT:    srai s4, s4, 16
; NOLH-NEXT:    srai s10, a3, 16
; NOLH-NEXT:    srai s11, a5, 16
; NOLH-NEXT:    srai s1, a7, 16
; NOLH-NEXT:    srai s3, t1, 16
; NOLH-NEXT:    srai s5, t2, 16
; NOLH-NEXT:    srai s6, t0, 16
; NOLH-NEXT:    srai s7, a6, 16
; NOLH-NEXT:    srai s8, a4, 16
; NOLH-NEXT:    srai s9, a2, 16
; NOLH-NEXT:    srai s0, a0, 16
; NOLH-NEXT:    call clobber
; NOLH-NEXT:    lw a0, 40(sp) # 4-byte Folded Reload
; NOLH-NEXT:    lw a1, 36(sp) # 4-byte Folded Reload
; NOLH-NEXT:    add a0, a0, a1
; NOLH-NEXT:    lw a1, 32(sp) # 4-byte Folded Reload
; NOLH-NEXT:    lw a2, 28(sp) # 4-byte Folded Reload
; NOLH-NEXT:    add a1, a1, a2
; NOLH-NEXT:    lw a2, 24(sp) # 4-byte Folded Reload
; NOLH-NEXT:    lw a3, 20(sp) # 4-byte Folded Reload
; NOLH-NEXT:    add a2, a2, a3
; NOLH-NEXT:    lw a3, 16(sp) # 4-byte Folded Reload
; NOLH-NEXT:    lw a4, 12(sp) # 4-byte Folded Reload
; NOLH-NEXT:    add a3, a3, a4
; NOLH-NEXT:    add s2, s2, s4
; NOLH-NEXT:    add s10, s10, s11
; NOLH-NEXT:    add s1, s1, s3
; NOLH-NEXT:    add s5, s5, s6
; NOLH-NEXT:    add s7, s7, s8
; NOLH-NEXT:    add s0, s9, s0
; NOLH-NEXT:    add a0, a0, a1
; NOLH-NEXT:    add a2, a2, a3
; NOLH-NEXT:    add s2, s2, s10
; NOLH-NEXT:    add s1, s1, s5
; NOLH-NEXT:    add s0, s7, s0
; NOLH-NEXT:    add a0, a0, a2
; NOLH-NEXT:    add s1, s2, s1
; NOLH-NEXT:    add a0, a0, s1
; NOLH-NEXT:    add a0, a0, s0
; NOLH-NEXT:    lw ra, 92(sp) # 4-byte Folded Reload
; NOLH-NEXT:    lw s0, 88(sp) # 4-byte Folded Reload
; NOLH-NEXT:    lw s1, 84(sp) # 4-byte Folded Reload
; NOLH-NEXT:    lw s2, 80(sp) # 4-byte Folded Reload
; NOLH-NEXT:    lw s3, 76(sp) # 4-byte Folded Reload
; NOLH-NEXT:    lw s4, 72(sp) # 4-byte Folded Reload
; NOLH-NEXT:    lw s5, 68(sp) # 4-byte Folded Reload
; NOLH-NEXT:    lw s6, 64(sp) # 4-byte Folded Reload
; NOLH-NEXT:    lw s7, 60(sp) # 4-byte Folded Reload
; NOLH-NEXT:    lw s8, 56(sp) # 4-byte Folded Reload
; NOLH-NEXT:    lw s9, 52(sp) # 4-byte Folded Reload
; NOLH-NEXT:    lw s10, 48(sp) # 4-byte Folded Reload
; NOLH-NEXT:    lw s11, 44(sp) # 4-byte Folded Reload
; NOLH-NEXT:    addi sp, sp, 96
; NOLH-NEXT:    jalr zero, 0(ra)
;
; NOLHU-LABEL: force_spill:
; NOLHU:       # %bb.0: # %entry
; NOLHU-NEXT:    addi sp, sp, -96
; NOLHU-NEXT:    sw ra, 92(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    sw s0, 88(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    sw s1, 84(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    sw s2, 80(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    sw s3, 76(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    sw s4, 72(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    sw s5, 68(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    sw s6, 64(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    sw s7, 60(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    sw s8, 56(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    sw s9, 52(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    sw s10, 48(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    sw s11, 44(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    lui s0, %hi(v0)
; NOLHU-NEXT:    lui s1, %hi(v1)
; NOLHU-NEXT:    lui s3, %hi(v2)
; NOLHU-NEXT:    lui s2, %hi(v3)
; NOLHU-NEXT:    lui a4, %hi(v4)
; NOLHU-NEXT:    lui a5, %hi(v5)
; NOLHU-NEXT:    lui a6, %hi(v6)
; NOLHU-NEXT:    lui a7, %hi(v7)
; NOLHU-NEXT:    lui t0, %hi(v8)
; NOLHU-NEXT:    lui t1, %hi(v9)
; NOLHU-NEXT:    lui t2, %hi(v10)
; NOLHU-NEXT:    lui t3, %hi(v11)
; NOLHU-NEXT:    lui t4, %hi(v12)
; NOLHU-NEXT:    lui t5, %hi(v13)
; NOLHU-NEXT:    lui t6, %hi(v14)
; NOLHU-NEXT:    lui ra, %hi(v15)
; NOLHU-NEXT:    lui a0, %hi(v16)
; NOLHU-NEXT:    lui a1, %hi(v17)
; NOLHU-NEXT:    lui a2, %hi(v18)
; NOLHU-NEXT:    lui a3, %hi(v19)
; NOLHU-NEXT:    lh s0, %lo(v0)(s0)
; NOLHU-NEXT:    sw s0, 40(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    lh s0, %lo(v1)(s1)
; NOLHU-NEXT:    sw s0, 36(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    lh s0, %lo(v2)(s3)
; NOLHU-NEXT:    sw s0, 32(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    lh s0, %lo(v3)(s2)
; NOLHU-NEXT:    sw s0, 28(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    lh a4, %lo(v4)(a4)
; NOLHU-NEXT:    sw a4, 24(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    lh a4, %lo(v5)(a5)
; NOLHU-NEXT:    sw a4, 20(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    lh a4, %lo(v6)(a6)
; NOLHU-NEXT:    sw a4, 16(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    lh a4, %lo(v7)(a7)
; NOLHU-NEXT:    sw a4, 12(sp) # 4-byte Folded Spill
; NOLHU-NEXT:    lh s1, %lo(v8)(t0)
; NOLHU-NEXT:    lh s6, %lo(v9)(t1)
; NOLHU-NEXT:    lh s7, %lo(v10)(t2)
; NOLHU-NEXT:    lh s8, %lo(v11)(t3)
; NOLHU-NEXT:    lh s9, %lo(v12)(t4)
; NOLHU-NEXT:    lh s3, %lo(v13)(t5)
; NOLHU-NEXT:    lh s4, %lo(v14)(t6)
; NOLHU-NEXT:    lh s5, %lo(v15)(ra)
; NOLHU-NEXT:    lh s10, %lo(v16)(a0)
; NOLHU-NEXT:    lh s2, %lo(v17)(a1)
; NOLHU-NEXT:    lh s11, %lo(v18)(a2)
; NOLHU-NEXT:    lh s0, %lo(v19)(a3)
; NOLHU-NEXT:    call clobber
; NOLHU-NEXT:    lw a0, 40(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    lw a1, 36(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    add a0, a0, a1
; NOLHU-NEXT:    lw a1, 32(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    lw a2, 28(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    add a1, a1, a2
; NOLHU-NEXT:    lw a2, 24(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    lw a3, 20(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    add a2, a2, a3
; NOLHU-NEXT:    lw a3, 16(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    lw a4, 12(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    add a3, a3, a4
; NOLHU-NEXT:    add s1, s1, s6
; NOLHU-NEXT:    add s7, s7, s8
; NOLHU-NEXT:    add s3, s9, s3
; NOLHU-NEXT:    add s4, s4, s5
; NOLHU-NEXT:    add s2, s10, s2
; NOLHU-NEXT:    add s0, s11, s0
; NOLHU-NEXT:    add a0, a0, a1
; NOLHU-NEXT:    add a2, a2, a3
; NOLHU-NEXT:    add s1, s1, s7
; NOLHU-NEXT:    add s3, s3, s4
; NOLHU-NEXT:    add s0, s2, s0
; NOLHU-NEXT:    add a0, a0, a2
; NOLHU-NEXT:    add s1, s1, s3
; NOLHU-NEXT:    add a0, a0, s1
; NOLHU-NEXT:    add a0, a0, s0
; NOLHU-NEXT:    lw ra, 92(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    lw s0, 88(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    lw s1, 84(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    lw s2, 80(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    lw s3, 76(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    lw s4, 72(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    lw s5, 68(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    lw s6, 64(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    lw s7, 60(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    lw s8, 56(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    lw s9, 52(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    lw s10, 48(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    lw s11, 44(sp) # 4-byte Folded Reload
; NOLHU-NEXT:    addi sp, sp, 96
; NOLHU-NEXT:    jalr zero, 0(ra)
;
; NOL-LABEL: force_spill:
; NOL:       # %bb.0: # %entry
; NOL-NEXT:    addi sp, sp, -96
; NOL-NEXT:    sw ra, 92(sp) # 4-byte Folded Spill
; NOL-NEXT:    sw s0, 88(sp) # 4-byte Folded Spill
; NOL-NEXT:    sw s1, 84(sp) # 4-byte Folded Spill
; NOL-NEXT:    sw s2, 80(sp) # 4-byte Folded Spill
; NOL-NEXT:    sw s3, 76(sp) # 4-byte Folded Spill
; NOL-NEXT:    sw s4, 72(sp) # 4-byte Folded Spill
; NOL-NEXT:    sw s5, 68(sp) # 4-byte Folded Spill
; NOL-NEXT:    sw s6, 64(sp) # 4-byte Folded Spill
; NOL-NEXT:    sw s7, 60(sp) # 4-byte Folded Spill
; NOL-NEXT:    sw s8, 56(sp) # 4-byte Folded Spill
; NOL-NEXT:    sw s9, 52(sp) # 4-byte Folded Spill
; NOL-NEXT:    sw s10, 48(sp) # 4-byte Folded Spill
; NOL-NEXT:    sw s11, 44(sp) # 4-byte Folded Spill
; NOL-NEXT:    lui a0, %hi(v0)
; NOL-NEXT:    lui a1, %hi(v1)
; NOL-NEXT:    lui a2, %hi(v2)
; NOL-NEXT:    lui a3, %hi(v3)
; NOL-NEXT:    lui a4, %hi(v4)
; NOL-NEXT:    lui a5, %hi(v5)
; NOL-NEXT:    lui a6, %hi(v6)
; NOL-NEXT:    lui a7, %hi(v7)
; NOL-NEXT:    lui t0, %hi(v8)
; NOL-NEXT:    lui t1, %hi(v9)
; NOL-NEXT:    lui t2, %hi(v10)
; NOL-NEXT:    lui t3, %hi(v11)
; NOL-NEXT:    lui t4, %hi(v12)
; NOL-NEXT:    lui t5, %hi(v13)
; NOL-NEXT:    lui s0, %hi(v14)
; NOL-NEXT:    lui s2, %hi(v15)
; NOL-NEXT:    lui s4, %hi(v16)
; NOL-NEXT:    lui s5, %hi(v17)
; NOL-NEXT:    lui s6, %hi(v18)
; NOL-NEXT:    lui s7, %hi(v19)
; NOL-NEXT:    addi s8, a0, %lo(v0)
; NOL-NEXT:    addi a1, a1, %lo(v1)
; NOL-NEXT:    addi s9, a2, %lo(v2)
; NOL-NEXT:    addi s10, a3, %lo(v3)
; NOL-NEXT:    addi s11, a4, %lo(v4)
; NOL-NEXT:    addi ra, a5, %lo(v5)
; NOL-NEXT:    addi a3, a6, %lo(v6)
; NOL-NEXT:    addi a5, a7, %lo(v7)
; NOL-NEXT:    addi a7, t0, %lo(v8)
; NOL-NEXT:    addi t1, t1, %lo(v9)
; NOL-NEXT:    addi s3, t2, %lo(v10)
; NOL-NEXT:    addi s1, t3, %lo(v11)
; NOL-NEXT:    addi t6, t4, %lo(v12)
; NOL-NEXT:    addi t4, t5, %lo(v13)
; NOL-NEXT:    addi t2, s0, %lo(v14)
; NOL-NEXT:    addi t0, s2, %lo(v15)
; NOL-NEXT:    addi a6, s4, %lo(v16)
; NOL-NEXT:    addi a4, s5, %lo(v17)
; NOL-NEXT:    addi a2, s6, %lo(v18)
; NOL-NEXT:    addi a0, s7, %lo(v19)
; NOL-NEXT:    andi t3, s8, -4
; NOL-NEXT:    andi t5, a1, -4
; NOL-NEXT:    sub s0, s8, t3
; NOL-NEXT:    lw t3, 0(t3)
; NOL-NEXT:    sub s2, a1, t5
; NOL-NEXT:    lw t5, 0(t5)
; NOL-NEXT:    slli s0, s0, 3
; NOL-NEXT:    srl a1, t3, s0
; NOL-NEXT:    andi t3, s9, -4
; NOL-NEXT:    slli s2, s2, 3
; NOL-NEXT:    srl s5, t5, s2
; NOL-NEXT:    andi t5, s10, -4
; NOL-NEXT:    sub s0, s9, t3
; NOL-NEXT:    lw t3, 0(t3)
; NOL-NEXT:    sub s2, s10, t5
; NOL-NEXT:    lw t5, 0(t5)
; NOL-NEXT:    slli s0, s0, 3
; NOL-NEXT:    srl s6, t3, s0
; NOL-NEXT:    andi t3, s11, -4
; NOL-NEXT:    slli s2, s2, 3
; NOL-NEXT:    srl s7, t5, s2
; NOL-NEXT:    andi t5, ra, -4
; NOL-NEXT:    sub s0, s11, t3
; NOL-NEXT:    lw t3, 0(t3)
; NOL-NEXT:    sub s2, ra, t5
; NOL-NEXT:    lw t5, 0(t5)
; NOL-NEXT:    slli s0, s0, 3
; NOL-NEXT:    srl s8, t3, s0
; NOL-NEXT:    andi s0, a3, -4
; NOL-NEXT:    slli s2, s2, 3
; NOL-NEXT:    srl t3, t5, s2
; NOL-NEXT:    andi t5, a5, -4
; NOL-NEXT:    sub a3, a3, s0
; NOL-NEXT:    lw s0, 0(s0)
; NOL-NEXT:    sub a5, a5, t5
; NOL-NEXT:    lw s2, 0(t5)
; NOL-NEXT:    slli a3, a3, 3
; NOL-NEXT:    srl t5, s0, a3
; NOL-NEXT:    andi a3, a7, -4
; NOL-NEXT:    slli a5, a5, 3
; NOL-NEXT:    srl s0, s2, a5
; NOL-NEXT:    andi a5, t1, -4
; NOL-NEXT:    sub a7, a7, a3
; NOL-NEXT:    lw a3, 0(a3)
; NOL-NEXT:    sub t1, t1, a5
; NOL-NEXT:    lw a5, 0(a5)
; NOL-NEXT:    slli a7, a7, 3
; NOL-NEXT:    srl s2, a3, a7
; NOL-NEXT:    andi a3, s3, -4
; NOL-NEXT:    slli t1, t1, 3
; NOL-NEXT:    srl s4, a5, t1
; NOL-NEXT:    andi a5, s1, -4
; NOL-NEXT:    sub a7, s3, a3
; NOL-NEXT:    lw a3, 0(a3)
; NOL-NEXT:    sub s1, s1, a5
; NOL-NEXT:    lw a5, 0(a5)
; NOL-NEXT:    slli a7, a7, 3
; NOL-NEXT:    srl a3, a3, a7
; NOL-NEXT:    andi a7, t6, -4
; NOL-NEXT:    slli s1, s1, 3
; NOL-NEXT:    srl a5, a5, s1
; NOL-NEXT:    andi t1, t4, -4
; NOL-NEXT:    sub t6, t6, a7
; NOL-NEXT:    lw a7, 0(a7)
; NOL-NEXT:    sub t4, t4, t1
; NOL-NEXT:    lw t1, 0(t1)
; NOL-NEXT:    slli t6, t6, 3
; NOL-NEXT:    srl a7, a7, t6
; NOL-NEXT:    andi t6, t2, -4
; NOL-NEXT:    slli t4, t4, 3
; NOL-NEXT:    srl t1, t1, t4
; NOL-NEXT:    andi t4, t0, -4
; NOL-NEXT:    sub t2, t2, t6
; NOL-NEXT:    lw t6, 0(t6)
; NOL-NEXT:    sub t0, t0, t4
; NOL-NEXT:    lw t4, 0(t4)
; NOL-NEXT:    slli t2, t2, 3
; NOL-NEXT:    srl t2, t6, t2
; NOL-NEXT:    andi t6, a6, -4
; NOL-NEXT:    slli t0, t0, 3
; NOL-NEXT:    srl t0, t4, t0
; NOL-NEXT:    andi t4, a4, -4
; NOL-NEXT:    sub a6, a6, t6
; NOL-NEXT:    lw t6, 0(t6)
; NOL-NEXT:    sub a4, a4, t4
; NOL-NEXT:    lw t4, 0(t4)
; NOL-NEXT:    slli a6, a6, 3
; NOL-NEXT:    srl a6, t6, a6
; NOL-NEXT:    andi t6, a2, -4
; NOL-NEXT:    slli a4, a4, 3
; NOL-NEXT:    srl a4, t4, a4
; NOL-NEXT:    andi t4, a0, -4
; NOL-NEXT:    sub a2, a2, t6
; NOL-NEXT:    lw t6, 0(t6)
; NOL-NEXT:    sub a0, a0, t4
; NOL-NEXT:    lw t4, 0(t4)
; NOL-NEXT:    slli a2, a2, 3
; NOL-NEXT:    slli a0, a0, 3
; NOL-NEXT:    srl a2, t6, a2
; NOL-NEXT:    srl a0, t4, a0
; NOL-NEXT:    slli a1, a1, 16
; NOL-NEXT:    slli s5, s5, 16
; NOL-NEXT:    slli s6, s6, 16
; NOL-NEXT:    slli s7, s7, 16
; NOL-NEXT:    slli s8, s8, 16
; NOL-NEXT:    slli t3, t3, 16
; NOL-NEXT:    slli t5, t5, 16
; NOL-NEXT:    slli s0, s0, 16
; NOL-NEXT:    slli s2, s2, 16
; NOL-NEXT:    slli s4, s4, 16
; NOL-NEXT:    slli a3, a3, 16
; NOL-NEXT:    slli a5, a5, 16
; NOL-NEXT:    slli a7, a7, 16
; NOL-NEXT:    slli t1, t1, 16
; NOL-NEXT:    slli t2, t2, 16
; NOL-NEXT:    slli t0, t0, 16
; NOL-NEXT:    slli a6, a6, 16
; NOL-NEXT:    slli a4, a4, 16
; NOL-NEXT:    slli a2, a2, 16
; NOL-NEXT:    slli a0, a0, 16
; NOL-NEXT:    srai a1, a1, 16
; NOL-NEXT:    sw a1, 40(sp) # 4-byte Folded Spill
; NOL-NEXT:    srai a1, s5, 16
; NOL-NEXT:    sw a1, 36(sp) # 4-byte Folded Spill
; NOL-NEXT:    srai a1, s6, 16
; NOL-NEXT:    sw a1, 32(sp) # 4-byte Folded Spill
; NOL-NEXT:    srai a1, s7, 16
; NOL-NEXT:    sw a1, 28(sp) # 4-byte Folded Spill
; NOL-NEXT:    srai a1, s8, 16
; NOL-NEXT:    sw a1, 24(sp) # 4-byte Folded Spill
; NOL-NEXT:    srai a1, t3, 16
; NOL-NEXT:    sw a1, 20(sp) # 4-byte Folded Spill
; NOL-NEXT:    srai a1, t5, 16
; NOL-NEXT:    sw a1, 16(sp) # 4-byte Folded Spill
; NOL-NEXT:    srai s0, s0, 16
; NOL-NEXT:    sw s0, 12(sp) # 4-byte Folded Spill
; NOL-NEXT:    srai s2, s2, 16
; NOL-NEXT:    srai s4, s4, 16
; NOL-NEXT:    srai s10, a3, 16
; NOL-NEXT:    srai s11, a5, 16
; NOL-NEXT:    srai s1, a7, 16
; NOL-NEXT:    srai s3, t1, 16
; NOL-NEXT:    srai s5, t2, 16
; NOL-NEXT:    srai s6, t0, 16
; NOL-NEXT:    srai s7, a6, 16
; NOL-NEXT:    srai s8, a4, 16
; NOL-NEXT:    srai s9, a2, 16
; NOL-NEXT:    srai s0, a0, 16
; NOL-NEXT:    call clobber
; NOL-NEXT:    lw a0, 40(sp) # 4-byte Folded Reload
; NOL-NEXT:    lw a1, 36(sp) # 4-byte Folded Reload
; NOL-NEXT:    add a0, a0, a1
; NOL-NEXT:    lw a1, 32(sp) # 4-byte Folded Reload
; NOL-NEXT:    lw a2, 28(sp) # 4-byte Folded Reload
; NOL-NEXT:    add a1, a1, a2
; NOL-NEXT:    lw a2, 24(sp) # 4-byte Folded Reload
; NOL-NEXT:    lw a3, 20(sp) # 4-byte Folded Reload
; NOL-NEXT:    add a2, a2, a3
; NOL-NEXT:    lw a3, 16(sp) # 4-byte Folded Reload
; NOL-NEXT:    lw a4, 12(sp) # 4-byte Folded Reload
; NOL-NEXT:    add a3, a3, a4
; NOL-NEXT:    add s2, s2, s4
; NOL-NEXT:    add s10, s10, s11
; NOL-NEXT:    add s1, s1, s3
; NOL-NEXT:    add s5, s5, s6
; NOL-NEXT:    add s7, s7, s8
; NOL-NEXT:    add s0, s9, s0
; NOL-NEXT:    add a0, a0, a1
; NOL-NEXT:    add a2, a2, a3
; NOL-NEXT:    add s2, s2, s10
; NOL-NEXT:    add s1, s1, s5
; NOL-NEXT:    add s0, s7, s0
; NOL-NEXT:    add a0, a0, a2
; NOL-NEXT:    add s1, s2, s1
; NOL-NEXT:    add a0, a0, s1
; NOL-NEXT:    add a0, a0, s0
; NOL-NEXT:    lw ra, 92(sp) # 4-byte Folded Reload
; NOL-NEXT:    lw s0, 88(sp) # 4-byte Folded Reload
; NOL-NEXT:    lw s1, 84(sp) # 4-byte Folded Reload
; NOL-NEXT:    lw s2, 80(sp) # 4-byte Folded Reload
; NOL-NEXT:    lw s3, 76(sp) # 4-byte Folded Reload
; NOL-NEXT:    lw s4, 72(sp) # 4-byte Folded Reload
; NOL-NEXT:    lw s5, 68(sp) # 4-byte Folded Reload
; NOL-NEXT:    lw s6, 64(sp) # 4-byte Folded Reload
; NOL-NEXT:    lw s7, 60(sp) # 4-byte Folded Reload
; NOL-NEXT:    lw s8, 56(sp) # 4-byte Folded Reload
; NOL-NEXT:    lw s9, 52(sp) # 4-byte Folded Reload
; NOL-NEXT:    lw s10, 48(sp) # 4-byte Folded Reload
; NOL-NEXT:    lw s11, 44(sp) # 4-byte Folded Reload
; NOL-NEXT:    addi sp, sp, 96
; NOL-NEXT:    jalr zero, 0(ra)
entry:
  ; Perform volatile loads from many distinct globals.
  %t0  = load volatile i16, i8* @v0
  %t1  = load volatile i16, i16* @v1
  %t2  = load volatile i16, i8* @v2
  %t3  = load volatile i16, i16* @v3
  %t4  = load volatile i16, i8* @v4
  %t5  = load volatile i16, i16* @v5
  %t6  = load volatile i16, i8* @v6
  %t7  = load volatile i16, i16* @v7
  %t8  = load volatile i16, i8* @v8
  %t9  = load volatile i16, i16* @v9
  %t10 = load volatile i16, i8* @v10
  %t11 = load volatile i16, i16* @v11
  %t12 = load volatile i16, i8* @v12
  %t13 = load volatile i16, i16* @v13
  %t14 = load volatile i16, i8* @v14
  %t15 = load volatile i16, i16* @v15
  %t16 = load volatile i16, i8* @v16
  %t17 = load volatile i16, i16* @v17
  %t18 = load volatile i16, i8* @v18
  %t19 = load volatile i16, i16* @v19

  ; Call an external function that can clobber caller-saved registers.
  call void @clobber()

  ; Use all loaded temps after the call so they're live across it.
  %s0  = add i16 %t0,  %t1
  %s1  = add i16 %t2,  %t3
  %s2  = add i16 %t4,  %t5
  %s3  = add i16 %t6,  %t7
  %s4  = add i16 %t8,  %t9
  %s5  = add i16 %t10, %t11
  %s6  = add i16 %t12, %t13
  %s7  = add i16 %t14, %t15
  %s8  = add i16 %t16, %t17
  %s9  = add i16 %t18, %t19

  %r0 = add i16 %s0, %s1
  %r1 = add i16 %s2, %s3
  %r2 = add i16 %s4, %s5
  %r3 = add i16 %s6, %s7
  %r4 = add i16 %s8, %s9

  %u0 = add i16 %r0, %r1
  %u1 = add i16 %r2, %r3
  %v  = add i16 %u0, %u1
  %res = add i16 %v, %r4

  ret i16 %res
}
