; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:     --disable-block-placement < %s \
; RUN:   | FileCheck -check-prefixes=ALL %s
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:     --disable-block-placement \
; RUN:     -mattr=+xkeysomnolb < %s \
; RUN:   | FileCheck -check-prefixes=NOLB %s

@global = global i8 97, align 1


define signext i8 @unaligned_global()  {
; ALL-LABEL: unaligned_global:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    lui a0, %hi(global)
; ALL-NEXT:    lb a0, %lo(global)(a0)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOLB-LABEL: unaligned_global:
; NOLB:       # %bb.0: # %entry
; NOLB-NEXT:    lui a0, %hi(global)
; NOLB-NEXT:    lbu a0, %lo(global)(a0)
; NOLB-NEXT:    slli a0, a0, 24
; NOLB-NEXT:    srai a0, a0, 24
; NOLB-NEXT:    jalr zero, 0(ra)
entry:
  %0 = load i8, ptr @global, align 1
  ret i8 %0
}
