; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:     --disable-block-placement < %s \
; RUN:   | FileCheck -check-prefixes=ALL %s
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:     --disable-block-placement \
; RUN:     -mattr=+xkeysomnolbu < %s \
; RUN:   | FileCheck -check-prefixes=NOLBU %s
; RUN: not llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:     --disable-block-placement \
; RUN:     -mattr=+xkeysomnolbu -mattr=+xkeysomnolb < %s

@global2 = global i8 97, align 1
@global = global { i32, i8, i8, [2 x i8] } { i32 0, i8 98, i8 99, [2 x i8] zeroinitializer }, align 4
@__const.stack_odd.ss = private unnamed_addr constant { i32, i8, i8, [2 x i8] } { i32 0, i8 99, i8 100, [2 x i8] zeroinitializer }, align 4

define zeroext i8 @unaligned_global() {
; ALL-LABEL: unaligned_global:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    lui a0, %hi(global2)
; ALL-NEXT:    lbu a0, %lo(global2)(a0)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOLBU-LABEL: unaligned_global:
; NOLBU:       # %bb.0: # %entry
; NOLBU-NEXT:    lui a0, %hi(global2)
; NOLBU-NEXT:    lb a0, %lo(global2)(a0)
; NOLBU-NEXT:    andi a0, a0, 255
; NOLBU-NEXT:    jalr zero, 0(ra)
entry:
  %0 = load i8, ptr @global2, align 1
  ret i8 %0
}

define zeroext i8 @global_even() {
; ALL-LABEL: global_even:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    lui a0, %hi(global+4)
; ALL-NEXT:    lbu a0, %lo(global+4)(a0)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOLBU-LABEL: global_even:
; NOLBU:       # %bb.0: # %entry
; NOLBU-NEXT:    lui a0, %hi(global+4)
; NOLBU-NEXT:    lb a0, %lo(global+4)(a0)
; NOLBU-NEXT:    andi a0, a0, 255
; NOLBU-NEXT:    jalr zero, 0(ra)
entry:
  %0 = load volatile i8, ptr getelementptr inbounds nuw (i8, ptr @global, i32 4), align 4
  ret i8 %0
}

define zeroext i8 @global_odd() {
; ALL-LABEL: global_odd:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    lui a0, %hi(global+5)
; ALL-NEXT:    lbu a0, %lo(global+5)(a0)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOLBU-LABEL: global_odd:
; NOLBU:       # %bb.0: # %entry
; NOLBU-NEXT:    lui a0, %hi(global+5)
; NOLBU-NEXT:    lb a0, %lo(global+5)(a0)
; NOLBU-NEXT:    andi a0, a0, 255
; NOLBU-NEXT:    jalr zero, 0(ra)
entry:
  %0 = load volatile i8, ptr getelementptr inbounds nuw (i8, ptr @global, i32 5), align 1
  ret i8 %0
}

define void @stack_even() {
; ALL-LABEL: stack_even:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    addi sp, sp, -16
; ALL-NEXT:    .cfi_def_cfa_offset 16
; ALL-NEXT:    lui a0, %hi(.L__const.stack_odd.ss)
; ALL-NEXT:    lw a1, %lo(.L__const.stack_odd.ss)(a0)
; ALL-NEXT:    addi a0, a0, %lo(.L__const.stack_odd.ss)
; ALL-NEXT:    sw a1, 12(sp)
; ALL-NEXT:    lbu a1, 4(a0)
; ALL-NEXT:    sb a1, 8(sp)
; ALL-NEXT:    lbu a1, 7(a0)
; ALL-NEXT:    sb a1, 6(sp)
; ALL-NEXT:    lbu a1, 5(a0)
; ALL-NEXT:    lbu a0, 6(a0)
; ALL-NEXT:    slli a0, a0, 8
; ALL-NEXT:    or a0, a0, a1
; ALL-NEXT:    sh a0, 4(sp)
; ALL-NEXT:    lbu zero, 8(sp)
; ALL-NEXT:    addi sp, sp, 16
; ALL-NEXT:    .cfi_def_cfa_offset 0
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOLBU-LABEL: stack_even:
; NOLBU:       # %bb.0: # %entry
; NOLBU-NEXT:    addi sp, sp, -16
; NOLBU-NEXT:    .cfi_def_cfa_offset 16
; NOLBU-NEXT:    lui a0, %hi(.L__const.stack_odd.ss)
; NOLBU-NEXT:    lw a1, %lo(.L__const.stack_odd.ss)(a0)
; NOLBU-NEXT:    addi a0, a0, %lo(.L__const.stack_odd.ss)
; NOLBU-NEXT:    sw a1, 12(sp)
; NOLBU-NEXT:    lb a1, 4(a0)
; NOLBU-NEXT:    andi a1, a1, 255
; NOLBU-NEXT:    sb a1, 8(sp)
; NOLBU-NEXT:    lb a1, 7(a0)
; NOLBU-NEXT:    andi a1, a1, 255
; NOLBU-NEXT:    sb a1, 6(sp)
; NOLBU-NEXT:    lb a1, 5(a0)
; NOLBU-NEXT:    lb a0, 6(a0)
; NOLBU-NEXT:    andi a1, a1, 255
; NOLBU-NEXT:    andi a0, a0, 255
; NOLBU-NEXT:    slli a0, a0, 8
; NOLBU-NEXT:    or a0, a0, a1
; NOLBU-NEXT:    sh a0, 4(sp)
; NOLBU-NEXT:    lb a0, 8(sp)
; NOLBU-NEXT:    andi a0, a0, 255
; NOLBU-NEXT:    addi sp, sp, 16
; NOLBU-NEXT:    .cfi_def_cfa_offset 0
; NOLBU-NEXT:    jalr zero, 0(ra)
entry:
  %ss.sroa.0 = alloca i32, align 4
  %ss.sroa.3 = alloca i8, align 4
  %ss.sroa.4 = alloca [3 x i8], align 1

  %ss.sroa.0.0.copyload = load volatile i32, ptr @__const.stack_odd.ss, align 4
  store volatile i32 %ss.sroa.0.0.copyload, ptr %ss.sroa.0, align 4
  %ss.sroa.3.0.copyload = load volatile i8, ptr getelementptr inbounds nuw (i8, ptr @__const.stack_odd.ss, i32 4), align 4
  store volatile i8 %ss.sroa.3.0.copyload, ptr %ss.sroa.3, align 4
  call void @llvm.memcpy.p0.p0.i32(ptr nonnull align 1 %ss.sroa.4, ptr align 1 getelementptr inbounds nuw (i8, ptr @__const.stack_odd.ss, i32 5), i32 3, i1 true)
  %ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.4. = load volatile i8, ptr %ss.sroa.3, align 4
  ret void
}

declare void @llvm.memcpy.p0.p0.i32(ptr noalias writeonly captures(none), ptr noalias readonly captures(none), i32, i1 immarg)

define zeroext i8 @stack_odd() {
; ALL-LABEL: stack_odd:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    addi sp, sp, -16
; ALL-NEXT:    .cfi_def_cfa_offset 16
; ALL-NEXT:    lui a0, %hi(.L__const.stack_odd.ss)
; ALL-NEXT:    lw a1, %lo(.L__const.stack_odd.ss)(a0)
; ALL-NEXT:    sw a1, 8(sp)
; ALL-NEXT:    addi a0, a0, %lo(.L__const.stack_odd.ss)
; ALL-NEXT:    lbu a1, 4(a0)
; ALL-NEXT:    sb a1, 12(sp)
; ALL-NEXT:    lbu a1, 5(a0)
; ALL-NEXT:    sb a1, 7(sp)
; ALL-NEXT:    lh a0, 6(a0)
; ALL-NEXT:    sh a0, 4(sp)
; ALL-NEXT:    lbu a0, 7(sp)
; ALL-NEXT:    addi sp, sp, 16
; ALL-NEXT:    .cfi_def_cfa_offset 0
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOLBU-LABEL: stack_odd:
; NOLBU:       # %bb.0: # %entry
; NOLBU-NEXT:    addi sp, sp, -16
; NOLBU-NEXT:    .cfi_def_cfa_offset 16
; NOLBU-NEXT:    lui a0, %hi(.L__const.stack_odd.ss)
; NOLBU-NEXT:    lw a1, %lo(.L__const.stack_odd.ss)(a0)
; NOLBU-NEXT:    sw a1, 8(sp)
; NOLBU-NEXT:    addi a0, a0, %lo(.L__const.stack_odd.ss)
; NOLBU-NEXT:    lb a1, 4(a0)
; NOLBU-NEXT:    andi a1, a1, 255
; NOLBU-NEXT:    sb a1, 12(sp)
; NOLBU-NEXT:    lb a1, 5(a0)
; NOLBU-NEXT:    andi a1, a1, 255
; NOLBU-NEXT:    sb a1, 7(sp)
; NOLBU-NEXT:    lh a0, 6(a0)
; NOLBU-NEXT:    sh a0, 4(sp)
; NOLBU-NEXT:    lb a0, 7(sp)
; NOLBU-NEXT:    andi a0, a0, 255
; NOLBU-NEXT:    addi sp, sp, 16
; NOLBU-NEXT:    .cfi_def_cfa_offset 0
; NOLBU-NEXT:    jalr zero, 0(ra)
entry:
  %ss.sroa.0 = alloca [5 x i8], align 4
  %ss.sroa.3 = alloca i8, align 1
  %ss.sroa.4 = alloca [2 x i8], align 2
  call void @llvm.memcpy.p0.p0.i32(ptr nonnull align 4 %ss.sroa.0, ptr align 4 @__const.stack_odd.ss, i32 5, i1 true)
  %ss.sroa.3.0.copyload = load volatile i8, ptr getelementptr inbounds nuw (i8, ptr @__const.stack_odd.ss, i32 5), align 1
  store volatile i8 %ss.sroa.3.0.copyload, ptr %ss.sroa.3, align 1
  call void @llvm.memcpy.p0.p0.i32(ptr nonnull align 2 %ss.sroa.4, ptr align 2 getelementptr inbounds nuw (i8, ptr @__const.stack_odd.ss, i32 6), i32 2, i1 true)
  %ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.5. = load volatile i8, ptr %ss.sroa.3, align 1
  ret i8 %ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.5.
}

define zeroext i8 @no_align(ptr %ptr) {
; ALL-LABEL: no_align:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    lbu a0, 0(a0)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOLBU-LABEL: no_align:
; NOLBU:       # %bb.0: # %entry
; NOLBU-NEXT:    lb a0, 0(a0)
; NOLBU-NEXT:    andi a0, a0, 255
; NOLBU-NEXT:    jalr zero, 0(ra)
entry:
  %0 = load i8, ptr %ptr, align 1
  ret i8 %0
}

define zeroext i8 @ptr_even(ptr %ptr) {
; ALL-LABEL: ptr_even:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    lbu a0, 4(a0)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOLBU-LABEL: ptr_even:
; NOLBU:       # %bb.0: # %entry
; NOLBU-NEXT:    lb a0, 4(a0)
; NOLBU-NEXT:    andi a0, a0, 255
; NOLBU-NEXT:    jalr zero, 0(ra)
entry:
  %b = getelementptr inbounds nuw i8, ptr %ptr, i32 4
  %0 = load i8, ptr %b, align 4
  ret i8 %0
}

define zeroext i8 @ptr_odd(ptr %ptr) {
; ALL-LABEL: ptr_odd:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    lbu a0, 5(a0)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOLBU-LABEL: ptr_odd:
; NOLBU:       # %bb.0: # %entry
; NOLBU-NEXT:    lb a0, 5(a0)
; NOLBU-NEXT:    andi a0, a0, 255
; NOLBU-NEXT:    jalr zero, 0(ra)
entry:
  %c = getelementptr inbounds nuw i8, ptr %ptr, i32 5
  %0 = load i8, ptr %c, align 1
  ret i8 %0
}
