; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:     --disable-block-placement < %s \
; RUN:   | FileCheck -check-prefixes=ALL %s
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:     --disable-block-placement \
; RUN:     -mattr=+xkeysomnolh < %s \
; RUN:   | FileCheck -check-prefixes=NOLH %s

%struct.mystruct = type { i32, i16, i16 }

@global2 = global i16 16962, align 2
@global =  global %struct.mystruct { i32 0, i16 4660, i16 22136 }, align 4
declare void @llvm.memcpy.p0.p0.i32(ptr noalias writeonly captures(none), ptr noalias readonly captures(none), i32, i1 immarg)

define signext i16 @unaligned_global() {
; ALL-LABEL: unaligned_global:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    lui a0, %hi(global2)
; ALL-NEXT:    lh a0, %lo(global2)(a0)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOLH-LABEL: unaligned_global:
; NOLH:       # %bb.0: # %entry
; NOLH-NEXT:    lui a0, %hi(global2)
; NOLH-NEXT:    lhu a0, %lo(global2)(a0)
; NOLH-NEXT:    slli a0, a0, 16
; NOLH-NEXT:    srai a0, a0, 16
; NOLH-NEXT:    jalr zero, 0(ra)
entry:
  %0 = load i16, ptr @global2, align 2
  ret i16 %0
}

define signext i16 @global_even() {
; ALL-LABEL: global_even:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    lui a0, %hi(global+4)
; ALL-NEXT:    lh a0, %lo(global+4)(a0)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOLH-LABEL: global_even:
; NOLH:       # %bb.0: # %entry
; NOLH-NEXT:    lui a0, %hi(global+4)
; NOLH-NEXT:    lhu a0, %lo(global+4)(a0)
; NOLH-NEXT:    slli a0, a0, 16
; NOLH-NEXT:    srai a0, a0, 16
; NOLH-NEXT:    jalr zero, 0(ra)
entry:
  %0 = load volatile i16, ptr getelementptr inbounds nuw (i8, ptr @global, i32 4), align 4
  ret i16 %0
}

define signext i16 @global_odd() {
; ALL-LABEL: global_odd:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    lui a0, %hi(global+6)
; ALL-NEXT:    lh a0, %lo(global+6)(a0)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOLH-LABEL: global_odd:
; NOLH:       # %bb.0: # %entry
; NOLH-NEXT:    lui a0, %hi(global+6)
; NOLH-NEXT:    lhu a0, %lo(global+6)(a0)
; NOLH-NEXT:    slli a0, a0, 16
; NOLH-NEXT:    srai a0, a0, 16
; NOLH-NEXT:    jalr zero, 0(ra)
entry:
  %0 = load volatile i16, ptr getelementptr inbounds nuw (i8, ptr @global, i32 6), align 2
  ret i16 %0
}

define signext i16 @stack_even() {
; ALL-LABEL: stack_even:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    addi sp, sp, -16
; ALL-NEXT:    .cfi_def_cfa_offset 16
; ALL-NEXT:    lui a0, %hi(global)
; ALL-NEXT:    lw a1, %lo(global)(a0)
; ALL-NEXT:    addi a0, a0, %lo(global)
; ALL-NEXT:    sw a1, 12(sp)
; ALL-NEXT:    lh a1, 4(a0)
; ALL-NEXT:    sh a1, 8(sp)
; ALL-NEXT:    lh a0, 6(a0)
; ALL-NEXT:    sh a0, 6(sp)
; ALL-NEXT:    lh a0, 8(sp)
; ALL-NEXT:    addi sp, sp, 16
; ALL-NEXT:    .cfi_def_cfa_offset 0
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOLH-LABEL: stack_even:
; NOLH:       # %bb.0: # %entry
; NOLH-NEXT:    addi sp, sp, -16
; NOLH-NEXT:    .cfi_def_cfa_offset 16
; NOLH-NEXT:    lui a0, %hi(global)
; NOLH-NEXT:    lw a1, %lo(global)(a0)
; NOLH-NEXT:    addi a0, a0, %lo(global)
; NOLH-NEXT:    sw a1, 12(sp)
; NOLH-NEXT:    lhu a1, 4(a0)
; NOLH-NEXT:    slli a1, a1, 16
; NOLH-NEXT:    srai a1, a1, 16
; NOLH-NEXT:    sh a1, 8(sp)
; NOLH-NEXT:    lhu a0, 6(a0)
; NOLH-NEXT:    slli a0, a0, 16
; NOLH-NEXT:    srai a0, a0, 16
; NOLH-NEXT:    sh a0, 6(sp)
; NOLH-NEXT:    lhu a0, 8(sp)
; NOLH-NEXT:    slli a0, a0, 16
; NOLH-NEXT:    srai a0, a0, 16
; NOLH-NEXT:    addi sp, sp, 16
; NOLH-NEXT:    .cfi_def_cfa_offset 0
; NOLH-NEXT:    jalr zero, 0(ra)
entry:
  %ss.sroa.0 = alloca i32, align 4
  %ss.sroa.3 = alloca i16, align 4
  %ss.sroa.4 = alloca i16, align 2
  %ss.sroa.0.0.copyload = load volatile i32, ptr @global, align 4
  store volatile i32 %ss.sroa.0.0.copyload, ptr %ss.sroa.0, align 4
  %ss.sroa.3.0.copyload = load volatile i16, ptr getelementptr inbounds nuw (i8, ptr @global, i32 4), align 4
  store volatile i16 %ss.sroa.3.0.copyload, ptr %ss.sroa.3, align 4
  %ss.sroa.4.0.copyload = load volatile i16, ptr getelementptr inbounds nuw (i8, ptr @global, i32 6), align 2
  store volatile i16 %ss.sroa.4.0.copyload, ptr %ss.sroa.4, align 2
  %ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.4. = load volatile i16, ptr %ss.sroa.3, align 4
  ret i16 %ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.4.
}

define signext i16 @stack_odd() {
; ALL-LABEL: stack_odd:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    addi sp, sp, -16
; ALL-NEXT:    .cfi_def_cfa_offset 16
; ALL-NEXT:    lui a0, %hi(global)
; ALL-NEXT:    lw a1, %lo(global)(a0)
; ALL-NEXT:    sw a1, 8(sp)
; ALL-NEXT:    addi a0, a0, %lo(global)
; ALL-NEXT:    lh a1, 4(a0)
; ALL-NEXT:    sh a1, 12(sp)
; ALL-NEXT:    lh a0, 6(a0)
; ALL-NEXT:    sh a0, 6(sp)
; ALL-NEXT:    lh a0, 6(sp)
; ALL-NEXT:    addi sp, sp, 16
; ALL-NEXT:    .cfi_def_cfa_offset 0
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOLH-LABEL: stack_odd:
; NOLH:       # %bb.0: # %entry
; NOLH-NEXT:    addi sp, sp, -16
; NOLH-NEXT:    .cfi_def_cfa_offset 16
; NOLH-NEXT:    lui a0, %hi(global)
; NOLH-NEXT:    lw a1, %lo(global)(a0)
; NOLH-NEXT:    sw a1, 8(sp)
; NOLH-NEXT:    addi a0, a0, %lo(global)
; NOLH-NEXT:    lhu a1, 4(a0)
; NOLH-NEXT:    slli a1, a1, 16
; NOLH-NEXT:    srai a1, a1, 16
; NOLH-NEXT:    sh a1, 12(sp)
; NOLH-NEXT:    lhu a0, 6(a0)
; NOLH-NEXT:    slli a0, a0, 16
; NOLH-NEXT:    srai a0, a0, 16
; NOLH-NEXT:    sh a0, 6(sp)
; NOLH-NEXT:    lhu a0, 6(sp)
; NOLH-NEXT:    slli a0, a0, 16
; NOLH-NEXT:    srai a0, a0, 16
; NOLH-NEXT:    addi sp, sp, 16
; NOLH-NEXT:    .cfi_def_cfa_offset 0
; NOLH-NEXT:    jalr zero, 0(ra)
entry:
  %ss.sroa.0 = alloca [6 x i8], align 4
  %ss.sroa.3 = alloca i16, align 2
  call void @llvm.memcpy.p0.p0.i32(ptr nonnull align 4 %ss.sroa.0, ptr align 4 @global, i32 6, i1 true)
  %ss.sroa.3.0.copyload = load volatile i16, ptr getelementptr inbounds nuw (i8, ptr @global, i32 6), align 2
  store volatile i16 %ss.sroa.3.0.copyload, ptr %ss.sroa.3, align 2
  %ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.6. = load volatile i16, ptr %ss.sroa.3, align 2
  ret i16 %ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.0.ss.sroa.3.6.
}

define signext i16 @no_align(ptr noundef readonly captures(none) %ptr) {
; ALL-LABEL: no_align:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    lh a0, 0(a0)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOLH-LABEL: no_align:
; NOLH:       # %bb.0: # %entry
; NOLH-NEXT:    lhu a0, 0(a0)
; NOLH-NEXT:    slli a0, a0, 16
; NOLH-NEXT:    srai a0, a0, 16
; NOLH-NEXT:    jalr zero, 0(ra)
entry:
  %0 = load i16, ptr %ptr, align 2
  ret i16 %0
}

define signext i16 @ptr_even(ptr noundef readonly captures(none) %ptr) {
; ALL-LABEL: ptr_even:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    lh a0, 4(a0)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOLH-LABEL: ptr_even:
; NOLH:       # %bb.0: # %entry
; NOLH-NEXT:    lhu a0, 4(a0)
; NOLH-NEXT:    slli a0, a0, 16
; NOLH-NEXT:    srai a0, a0, 16
; NOLH-NEXT:    jalr zero, 0(ra)
entry:
  %b = getelementptr inbounds nuw i8, ptr %ptr, i32 4
  %0 = load i16, ptr %b, align 4
  ret i16 %0
}

define signext i16 @ptr_odd(ptr noundef readonly captures(none) %ptr) {
; ALL-LABEL: ptr_odd:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    lh a0, 6(a0)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOLH-LABEL: ptr_odd:
; NOLH:       # %bb.0: # %entry
; NOLH-NEXT:    lhu a0, 6(a0)
; NOLH-NEXT:    slli a0, a0, 16
; NOLH-NEXT:    srai a0, a0, 16
; NOLH-NEXT:    jalr zero, 0(ra)
entry:
  %c = getelementptr inbounds nuw i8, ptr %ptr, i32 6
  %0 = load i16, ptr %c, align 2
  ret i16 %0
}
