; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV32I %s
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:   -mattr=+xkeysomnoor < %s \
; RUN:   | FileCheck -check-prefix=RV32I_NO %s

define i32 @f(i32 %a, i32 %b) nounwind {
; RV32I-LABEL: f:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    or a0, a1, a0
; RV32I-NEXT:    jalr zero, 0(ra)
;
; RV32I_NO-LABEL: f:
; RV32I_NO:       # %bb.0: # %entry
; RV32I_NO-NEXT:    xori a1, a1, -1
; RV32I_NO-NEXT:    xori a0, a0, -1
; RV32I_NO-NEXT:    and a0, a1, a0
; RV32I_NO-NEXT:    xori a0, a0, -1
; RV32I_NO-NEXT:    jalr zero, 0(ra)
entry:
  %or = or i32 %b, %a
  ret i32 %or
}
