; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:     --disable-block-placement < %s \
; RUN:   | FileCheck -check-prefixes=ALL %s
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:     --disable-block-placement \
; RUN:     -mattr=+xkeysomnosb < %s \
; RUN:   | FileCheck -check-prefixes=NOSB %s

%struct.mystruct = type { i32, i8, i8 }

@global2 =  global i8 0, align 1
@global = global %struct.mystruct zeroinitializer, align 4

define void @unaligned_global(i8 zeroext %v) {
; ALL-LABEL: unaligned_global:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    lui a1, %hi(global2)
; ALL-NEXT:    sb a0, %lo(global2)(a1)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOSB-LABEL: unaligned_global:
; NOSB:       # %bb.0: # %entry
; NOSB-NEXT:    lui a1, %hi(global2)
; NOSB-NEXT:    andi a0, a0, 255
; NOSB-NEXT:    addi a2, zero, 255
; NOSB-NEXT:    addi a1, a1, %lo(global2)
; NOSB-NEXT:    andi a3, a1, -2
; NOSB-NEXT:    lh a4, 0(a3)
; NOSB-NEXT:    sltu a1, a3, a1
; NOSB-NEXT:    slli a1, a1, 3
; NOSB-NEXT:    sll a2, a2, a1
; NOSB-NEXT:    xori a2, a2, -1
; NOSB-NEXT:    sll a0, a0, a1
; NOSB-NEXT:    and a2, a4, a2
; NOSB-NEXT:    or a0, a2, a0
; NOSB-NEXT:    sh a0, 0(a3)
; NOSB-NEXT:    jalr zero, 0(ra)
entry:
  store i8 %v, ptr @global2, align 1, !tbaa !6
  ret void
}

define void @global_even(i8 zeroext %v) {
; ALL-LABEL: global_even:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    lui a1, %hi(global+4)
; ALL-NEXT:    sb a0, %lo(global+4)(a1)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOSB-LABEL: global_even:
; NOSB:       # %bb.0: # %entry
; NOSB-NEXT:    lui a1, %hi(global+4)
; NOSB-NEXT:    lh a2, %lo(global+4)(a1)
; NOSB-NEXT:    andi a0, a0, 255
; NOSB-NEXT:    andi a2, a2, -256
; NOSB-NEXT:    or a0, a2, a0
; NOSB-NEXT:    sh a0, %lo(global+4)(a1)
; NOSB-NEXT:    jalr zero, 0(ra)
entry:
  store volatile i8 %v, ptr getelementptr inbounds nuw (i8, ptr @global, i32 4), align 4, !tbaa !9
  ret void
}

define void @global_odd(i8 zeroext %v) {
; ALL-LABEL: global_odd:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    lui a1, %hi(global+5)
; ALL-NEXT:    sb a0, %lo(global+5)(a1)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOSB-LABEL: global_odd:
; NOSB:       # %bb.0: # %entry
; NOSB-NEXT:    lui a1, %hi(global+5)
; NOSB-NEXT:    lh a2, %lo(global+4)(a1)
; NOSB-NEXT:    andi a0, a0, 255
; NOSB-NEXT:    andi a2, a2, 255
; NOSB-NEXT:    slli a0, a0, 8
; NOSB-NEXT:    or a0, a2, a0
; NOSB-NEXT:    sh a0, %lo(global+4)(a1)
; NOSB-NEXT:    jalr zero, 0(ra)
entry:
  store volatile i8 %v, ptr getelementptr inbounds nuw (i8, ptr @global, i32 5), align 1, !tbaa !12
  ret void
}

define void @stack_even(i8 zeroext %v) {
; ALL-LABEL: stack_even:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    addi sp, sp, -16
; ALL-NEXT:    .cfi_def_cfa_offset 16
; ALL-NEXT:    sb a0, 12(sp)
; ALL-NEXT:    addi sp, sp, 16
; ALL-NEXT:    .cfi_def_cfa_offset 0
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOSB-LABEL: stack_even:
; NOSB:       # %bb.0: # %entry
; NOSB-NEXT:    addi sp, sp, -16
; NOSB-NEXT:    .cfi_def_cfa_offset 16
; NOSB-NEXT:    lh a1, 12(sp)
; NOSB-NEXT:    andi a0, a0, 255
; NOSB-NEXT:    andi a1, a1, -256
; NOSB-NEXT:    or a0, a1, a0
; NOSB-NEXT:    sh a0, 12(sp)
; NOSB-NEXT:    addi sp, sp, 16
; NOSB-NEXT:    .cfi_def_cfa_offset 0
; NOSB-NEXT:    jalr zero, 0(ra)
entry:
  %ss.sroa.2 = alloca i8, align 4
  store volatile i8 %v, ptr %ss.sroa.2, align 4, !tbaa !9
  ret void
}

define void @stack_odd(i8 zeroext %v) {
; ALL-LABEL: stack_odd:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    addi sp, sp, -16
; ALL-NEXT:    .cfi_def_cfa_offset 16
; ALL-NEXT:    sb a0, 15(sp)
; ALL-NEXT:    addi sp, sp, 16
; ALL-NEXT:    .cfi_def_cfa_offset 0
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOSB-LABEL: stack_odd:
; NOSB:       # %bb.0: # %entry
; NOSB-NEXT:    addi sp, sp, -16
; NOSB-NEXT:    .cfi_def_cfa_offset 16
; NOSB-NEXT:    andi a0, a0, 255
; NOSB-NEXT:    addi a1, sp, 15
; NOSB-NEXT:    addi a2, zero, 255
; NOSB-NEXT:    andi a3, a1, -2
; NOSB-NEXT:    lh a4, 0(a3)
; NOSB-NEXT:    sltu a1, a3, a1
; NOSB-NEXT:    slli a1, a1, 3
; NOSB-NEXT:    sll a2, a2, a1
; NOSB-NEXT:    xori a2, a2, -1
; NOSB-NEXT:    sll a0, a0, a1
; NOSB-NEXT:    and a2, a4, a2
; NOSB-NEXT:    or a0, a2, a0
; NOSB-NEXT:    sh a0, 0(a3)
; NOSB-NEXT:    addi sp, sp, 16
; NOSB-NEXT:    .cfi_def_cfa_offset 0
; NOSB-NEXT:    jalr zero, 0(ra)
entry:
  %ss.sroa.2 = alloca i8, align 1
  store volatile i8 %v, ptr %ss.sroa.2, align 1, !tbaa !12
  ret void
}

define void @no_align(ptr %ptr, i8 zeroext %v) {
; ALL-LABEL: no_align:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    sb a1, 0(a0)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOSB-LABEL: no_align:
; NOSB:       # %bb.0: # %entry
; NOSB-NEXT:    andi a1, a1, 255
; NOSB-NEXT:    addi a2, zero, 255
; NOSB-NEXT:    andi a3, a0, -2
; NOSB-NEXT:    lh a4, 0(a3)
; NOSB-NEXT:    sltu a0, a3, a0
; NOSB-NEXT:    slli a0, a0, 3
; NOSB-NEXT:    sll a2, a2, a0
; NOSB-NEXT:    xori a2, a2, -1
; NOSB-NEXT:    sll a0, a1, a0
; NOSB-NEXT:    and a2, a4, a2
; NOSB-NEXT:    or a0, a2, a0
; NOSB-NEXT:    sh a0, 0(a3)
; NOSB-NEXT:    jalr zero, 0(ra)
entry:
  store i8 %v, ptr %ptr, align 1, !tbaa !6
  ret void
}

define void @ptr_even(ptr writeonly captures(none) initializes((4, 5)) %ptr, i8 zeroext %v) {
; ALL-LABEL: ptr_even:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    sb a1, 4(a0)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOSB-LABEL: ptr_even:
; NOSB:       # %bb.0: # %entry
; NOSB-NEXT:    lh a2, 4(a0)
; NOSB-NEXT:    andi a1, a1, 255
; NOSB-NEXT:    andi a2, a2, -256
; NOSB-NEXT:    or a1, a2, a1
; NOSB-NEXT:    sh a1, 4(a0)
; NOSB-NEXT:    jalr zero, 0(ra)
entry:
  %b = getelementptr inbounds nuw i8, ptr %ptr, i32 4
  store i8 %v, ptr %b, align 4, !tbaa !9
  ret void
}

define void @ptr_odd(ptr writeonly captures(none) initializes((5, 6)) %ptr, i8 zeroext %v) {
; ALL-LABEL: ptr_odd:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    sb a1, 5(a0)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOSB-LABEL: ptr_odd:
; NOSB:       # %bb.0: # %entry
; NOSB-NEXT:    andi a1, a1, 255
; NOSB-NEXT:    addi a0, a0, 5
; NOSB-NEXT:    addi a2, zero, 255
; NOSB-NEXT:    andi a3, a0, -2
; NOSB-NEXT:    lh a4, 0(a3)
; NOSB-NEXT:    sltu a0, a3, a0
; NOSB-NEXT:    slli a0, a0, 3
; NOSB-NEXT:    sll a2, a2, a0
; NOSB-NEXT:    xori a2, a2, -1
; NOSB-NEXT:    sll a0, a1, a0
; NOSB-NEXT:    and a2, a4, a2
; NOSB-NEXT:    or a0, a2, a0
; NOSB-NEXT:    sh a0, 0(a3)
; NOSB-NEXT:    jalr zero, 0(ra)
entry:
  %c = getelementptr inbounds nuw i8, ptr %ptr, i32 5
  store i8 %v, ptr %c, align 1, !tbaa !12
  ret void
}

!6 = !{!7, !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}
!9 = !{!10, !7, i64 4}
!10 = !{!"mystruct", !11, i64 0, !7, i64 4, !7, i64 5}
!11 = !{!"int", !7, i64 0}
!12 = !{!10, !7, i64 5}
