; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:     --disable-block-placement < %s \
; RUN:   | FileCheck -check-prefixes=ALL %s
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:     --disable-block-placement \
; RUN:     -mattr=+xkeysomnosh < %s \
; RUN:   | FileCheck -check-prefixes=NOSH %s

%struct.mystruct = type { i32, i16, i16 }

@global2 =  global i16 0, align 2
@global =  global %struct.mystruct zeroinitializer, align 4

define void @unaligned_global(i16 signext %v) {
; ALL-LABEL: unaligned_global:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    lui a1, %hi(global2)
; ALL-NEXT:    sh a0, %lo(global2)(a1)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOSH-LABEL: unaligned_global:
; NOSH:       # %bb.0: # %entry
; NOSH-NEXT:    lui a1, %hi(global2)
; NOSH-NEXT:    lui a2, 16
; NOSH-NEXT:    addi a2, a2, -1
; NOSH-NEXT:    addi a1, a1, %lo(global2)
; NOSH-NEXT:    and a0, a2, a0
; NOSH-NEXT:    andi a3, a1, -4
; NOSH-NEXT:    lw a4, 0(a3)
; NOSH-NEXT:    sltu a1, a3, a1
; NOSH-NEXT:    slli a1, a1, 4
; NOSH-NEXT:    sll a2, a2, a1
; NOSH-NEXT:    xori a2, a2, -1
; NOSH-NEXT:    sll a0, a0, a1
; NOSH-NEXT:    and a2, a4, a2
; NOSH-NEXT:    or a0, a2, a0
; NOSH-NEXT:    sw a0, 0(a3)
; NOSH-NEXT:    jalr zero, 0(ra)
entry:
  store i16 %v, ptr @global2, align 2
  ret void
}

define void @global_even(i16 signext %v) {
; ALL-LABEL: global_even:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    lui a1, %hi(global+4)
; ALL-NEXT:    sh a0, %lo(global+4)(a1)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOSH-LABEL: global_even:
; NOSH:       # %bb.0: # %entry
; NOSH-NEXT:    lui a1, %hi(global+4)
; NOSH-NEXT:    lui a2, 16
; NOSH-NEXT:    addi a2, a2, -1
; NOSH-NEXT:    addi a1, a1, %lo(global+4)
; NOSH-NEXT:    and a0, a2, a0
; NOSH-NEXT:    andi a3, a1, -4
; NOSH-NEXT:    lw a4, 0(a3)
; NOSH-NEXT:    sltu a1, a3, a1
; NOSH-NEXT:    slli a1, a1, 4
; NOSH-NEXT:    sll a2, a2, a1
; NOSH-NEXT:    xori a2, a2, -1
; NOSH-NEXT:    sll a0, a0, a1
; NOSH-NEXT:    and a2, a4, a2
; NOSH-NEXT:    or a0, a2, a0
; NOSH-NEXT:    sw a0, 0(a3)
; NOSH-NEXT:    jalr zero, 0(ra)
entry:
  store volatile i16 %v, ptr getelementptr inbounds nuw (i8, ptr @global, i32 4), align 4
  ret void
}

define void @global_odd(i16 signext %v) {
; ALL-LABEL: global_odd:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    lui a1, %hi(global+6)
; ALL-NEXT:    sh a0, %lo(global+6)(a1)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOSH-LABEL: global_odd:
; NOSH:       # %bb.0: # %entry
; NOSH-NEXT:    lui a1, %hi(global+6)
; NOSH-NEXT:    lui a2, 16
; NOSH-NEXT:    addi a2, a2, -1
; NOSH-NEXT:    addi a1, a1, %lo(global+6)
; NOSH-NEXT:    and a0, a2, a0
; NOSH-NEXT:    andi a3, a1, -4
; NOSH-NEXT:    lw a4, 0(a3)
; NOSH-NEXT:    sltu a1, a3, a1
; NOSH-NEXT:    slli a1, a1, 4
; NOSH-NEXT:    sll a2, a2, a1
; NOSH-NEXT:    xori a2, a2, -1
; NOSH-NEXT:    sll a0, a0, a1
; NOSH-NEXT:    and a2, a4, a2
; NOSH-NEXT:    or a0, a2, a0
; NOSH-NEXT:    sw a0, 0(a3)
; NOSH-NEXT:    jalr zero, 0(ra)
entry:
  store volatile i16 %v, ptr getelementptr inbounds nuw (i8, ptr @global, i32 6), align 2
  ret void
}

define void @stack_even(i16 signext %v) {
; ALL-LABEL: stack_even:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    addi sp, sp, -16
; ALL-NEXT:    .cfi_def_cfa_offset 16
; ALL-NEXT:    sh a0, 12(sp)
; ALL-NEXT:    addi sp, sp, 16
; ALL-NEXT:    .cfi_def_cfa_offset 0
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOSH-LABEL: stack_even:
; NOSH:       # %bb.0: # %entry
; NOSH-NEXT:    addi sp, sp, -16
; NOSH-NEXT:    .cfi_def_cfa_offset 16
; NOSH-NEXT:    lui a1, 16
; NOSH-NEXT:    addi a2, sp, 12
; NOSH-NEXT:    addi a1, a1, -1
; NOSH-NEXT:    andi a3, a2, -4
; NOSH-NEXT:    and a0, a1, a0
; NOSH-NEXT:    lw a4, 0(a3)
; NOSH-NEXT:    sltu a2, a3, a2
; NOSH-NEXT:    slli a2, a2, 4
; NOSH-NEXT:    sll a1, a1, a2
; NOSH-NEXT:    xori a1, a1, -1
; NOSH-NEXT:    sll a0, a0, a2
; NOSH-NEXT:    and a1, a4, a1
; NOSH-NEXT:    or a0, a1, a0
; NOSH-NEXT:    sw a0, 0(a3)
; NOSH-NEXT:    addi sp, sp, 16
; NOSH-NEXT:    .cfi_def_cfa_offset 0
; NOSH-NEXT:    jalr zero, 0(ra)
entry:
  %ss.sroa.2 = alloca i16, align 4
  store volatile i16 %v, ptr %ss.sroa.2, align 4
  ret void
}

define void @stack_odd(i16 signext %v) {
; ALL-LABEL: stack_odd:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    addi sp, sp, -16
; ALL-NEXT:    .cfi_def_cfa_offset 16
; ALL-NEXT:    sh a0, 14(sp)
; ALL-NEXT:    addi sp, sp, 16
; ALL-NEXT:    .cfi_def_cfa_offset 0
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOSH-LABEL: stack_odd:
; NOSH:       # %bb.0: # %entry
; NOSH-NEXT:    addi sp, sp, -16
; NOSH-NEXT:    .cfi_def_cfa_offset 16
; NOSH-NEXT:    lui a1, 16
; NOSH-NEXT:    addi a2, sp, 14
; NOSH-NEXT:    addi a1, a1, -1
; NOSH-NEXT:    andi a3, a2, -4
; NOSH-NEXT:    and a0, a1, a0
; NOSH-NEXT:    lw a4, 0(a3)
; NOSH-NEXT:    sltu a2, a3, a2
; NOSH-NEXT:    slli a2, a2, 4
; NOSH-NEXT:    sll a1, a1, a2
; NOSH-NEXT:    xori a1, a1, -1
; NOSH-NEXT:    sll a0, a0, a2
; NOSH-NEXT:    and a1, a4, a1
; NOSH-NEXT:    or a0, a1, a0
; NOSH-NEXT:    sw a0, 0(a3)
; NOSH-NEXT:    addi sp, sp, 16
; NOSH-NEXT:    .cfi_def_cfa_offset 0
; NOSH-NEXT:    jalr zero, 0(ra)
entry:
  %ss.sroa.2 = alloca i16, align 2
  store volatile i16 %v, ptr %ss.sroa.2, align 2
  ret void
}

define void @no_align(ptr %ptr, i16 signext %v) {
; ALL-LABEL: no_align:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    sh a1, 0(a0)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOSH-LABEL: no_align:
; NOSH:       # %bb.0: # %entry
; NOSH-NEXT:    lui a2, 16
; NOSH-NEXT:    addi a2, a2, -1
; NOSH-NEXT:    andi a3, a0, -4
; NOSH-NEXT:    and a1, a2, a1
; NOSH-NEXT:    lw a4, 0(a3)
; NOSH-NEXT:    sltu a0, a3, a0
; NOSH-NEXT:    slli a0, a0, 4
; NOSH-NEXT:    sll a2, a2, a0
; NOSH-NEXT:    xori a2, a2, -1
; NOSH-NEXT:    sll a0, a1, a0
; NOSH-NEXT:    and a2, a4, a2
; NOSH-NEXT:    or a0, a2, a0
; NOSH-NEXT:    sw a0, 0(a3)
; NOSH-NEXT:    jalr zero, 0(ra)
entry:
  store i16 %v, ptr %ptr, align 2
  ret void
}

define void @ptr_even(ptr %ptr, i16 signext %v) {
; ALL-LABEL: ptr_even:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    sh a1, 4(a0)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOSH-LABEL: ptr_even:
; NOSH:       # %bb.0: # %entry
; NOSH-NEXT:    lui a2, 16
; NOSH-NEXT:    addi a0, a0, 4
; NOSH-NEXT:    addi a2, a2, -1
; NOSH-NEXT:    andi a3, a0, -4
; NOSH-NEXT:    and a1, a2, a1
; NOSH-NEXT:    lw a4, 0(a3)
; NOSH-NEXT:    sltu a0, a3, a0
; NOSH-NEXT:    slli a0, a0, 4
; NOSH-NEXT:    sll a2, a2, a0
; NOSH-NEXT:    xori a2, a2, -1
; NOSH-NEXT:    sll a0, a1, a0
; NOSH-NEXT:    and a2, a4, a2
; NOSH-NEXT:    or a0, a2, a0
; NOSH-NEXT:    sw a0, 0(a3)
; NOSH-NEXT:    jalr zero, 0(ra)
entry:
  %b = getelementptr inbounds nuw i8, ptr %ptr, i32 4
  store i16 %v, ptr %b, align 4
  ret void
}

define void @ptr_odd(ptr %ptr, i16 signext %v) {
; ALL-LABEL: ptr_odd:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    sh a1, 6(a0)
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOSH-LABEL: ptr_odd:
; NOSH:       # %bb.0: # %entry
; NOSH-NEXT:    lui a2, 16
; NOSH-NEXT:    addi a0, a0, 6
; NOSH-NEXT:    addi a2, a2, -1
; NOSH-NEXT:    andi a3, a0, -4
; NOSH-NEXT:    and a1, a2, a1
; NOSH-NEXT:    lw a4, 0(a3)
; NOSH-NEXT:    sltu a0, a3, a0
; NOSH-NEXT:    slli a0, a0, 4
; NOSH-NEXT:    sll a2, a2, a0
; NOSH-NEXT:    xori a2, a2, -1
; NOSH-NEXT:    sll a0, a1, a0
; NOSH-NEXT:    and a2, a4, a2
; NOSH-NEXT:    or a0, a2, a0
; NOSH-NEXT:    sw a0, 0(a3)
; NOSH-NEXT:    jalr zero, 0(ra)
entry:
  %c = getelementptr inbounds nuw i8, ptr %ptr, i32 6
  store i16 %v, ptr %c, align 2
  ret void
}
