; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -riscv-no-aliases < %s \
; RUN:   | FileCheck -check-prefix=RV32I %s
; RUN: llc -mtriple=riscv32 -riscv-no-aliases -mattr=+xkeysomnosltiu < %s \
; RUN:   | FileCheck -check-prefix=RV32I_NO %s

define i32 @f(i32 %x) nounwind {
; RV32I-LABEL: f:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    sltiu a0, a0, 43
; RV32I-NEXT:    jalr zero, 0(ra)
;
; RV32I_NO-LABEL: f:
; RV32I_NO:       # %bb.0: # %entry
; RV32I_NO-NEXT:    addi a1, zero, 43
; RV32I_NO-NEXT:    sltu a0, a0, a1
; RV32I_NO-NEXT:    jalr zero, 0(ra)

entry:
  %cmp = icmp ult i32 %x, 43
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}


define i32 @g(i32 %x) nounwind {
; RV32I-LABEL: g:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    sltiu a1, a0, 1
; RV32I-NEXT:    add a0, a0, a1
; RV32I-NEXT:    jalr zero, 0(ra)
;
; RV32I_NO-LABEL: g:
; RV32I_NO:       # %bb.0: # %entry
; RV32I_NO-NEXT:    addi a1, a0, -1
; RV32I_NO-NEXT:    bgeu a1, zero, .LBB1_2
; RV32I_NO-NEXT:  # %bb.1: # %entry
; RV32I_NO-NEXT:    addi a1, zero, 1
; RV32I_NO-NEXT:    add a0, a0, a1
; RV32I_NO-NEXT:    jalr zero, 0(ra)
; RV32I_NO-NEXT:  .LBB1_2: # %entry
; RV32I_NO-NEXT:    jalr zero, 0(ra)

entry:
  %y = tail call i32 @llvm.umax.i32(i32 %x, i32 1)
  ret i32 %y
}





