; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -riscv-no-aliases < %s  \
; RUN:   | FileCheck -check-prefix=RV32I %s
;
; RUN: llc -mtriple=riscv32 -riscv-no-aliases       \
; RUN:     -mattr=+xkeysomnosltu < %s               \
; RUN:   | FileCheck -check-prefix=RV32I_NO_SLTU %s

define i32 @f(i32 %x, i32 %y) nounwind {
; RV32I-LABEL: f:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    sltu a0, a0, a1
; RV32I-NEXT:    jalr zero, 0(ra)
;
; RV32I_NO_SLTU-LABEL: f:
; RV32I_NO_SLTU:       # %bb.0: # %entry
; RV32I_NO_SLTU-NEXT:    bltu a0, a1, .LBB0_2
; RV32I_NO_SLTU-NEXT:  # %bb.1: # %entry
; RV32I_NO_SLTU-NEXT:    addi a0, zero, 0
; RV32I_NO_SLTU-NEXT:    jalr zero, 0(ra)
; RV32I_NO_SLTU-NEXT:  .LBB0_2: # %entry
; RV32I_NO_SLTU-NEXT:    addi a0, zero, 1
; RV32I_NO_SLTU-NEXT:    jalr zero, 0(ra)

entry:
  %cmp = icmp ult i32 %x, %y
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}
