; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -riscv-no-aliases < %s | FileCheck -check-prefix=ALL %s

; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:     -mattr=+xkeysomnosrl < %s | FileCheck -check-prefix=NOSRL %s

define i32 @f(i32 %x, i32 %y) nounwind {
; ALL-LABEL: f:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    srl a0, a0, a1
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOSRL-LABEL: f:
; NOSRL:       # %bb.0: # %entry
; NOSRL-NEXT:    sra a0, a0, a1
; NOSRL-NEXT:    andi a1, a1, 31
; NOSRL-NEXT:    addi a2, zero, 1
; NOSRL-NEXT:    addi a3, zero, 31
; NOSRL-NEXT:    addi a4, zero, 32
; NOSRL-NEXT:    sub a3, a3, a1
; NOSRL-NEXT:    sub a1, a1, a4
; NOSRL-NEXT:    sll a2, a2, a3
; NOSRL-NEXT:    add a2, a2, a2
; NOSRL-NEXT:    addi a2, a2, -1
; NOSRL-NEXT:    srai a1, a1, 31
; NOSRL-NEXT:    and a1, a2, a1
; NOSRL-NEXT:    and a0, a0, a1
; NOSRL-NEXT:    jalr zero, 0(ra)
entry:
  %shr = lshr i32 %x, %y
  ret i32 %shr
}
