; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -riscv-no-aliases < %s | FileCheck -check-prefix=ALL %s

; RUN: llc -mtriple=riscv32 -riscv-no-aliases -verify-machineinstrs \
; RUN:     -mattr=+xkeysomnosrl < %s | FileCheck -check-prefix=NOSRL %s

define i32 @f(i32 %x, i32 %y) nounwind {
; ALL-LABEL: f:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    srl a0, a0, a1
; ALL-NEXT:    jalr zero, 0(ra)
;
; NOSRL-LABEL: f:
; NOSRL:       # %bb.0: # %entry
; NOSRL-NEXT:    sra a0, a0, a1
; NOSRL-NEXT:    andi a1, a1, 31
; NOSRL-NEXT:    sltu a2, zero, a1
; NOSRL-NEXT:    slli a3, a2, 31
; NOSRL-NEXT:    sub a1, a1, a2
; NOSRL-NEXT:    sra a1, a3, a1
; NOSRL-NEXT:    xori a1, a1, -1
; NOSRL-NEXT:    and a0, a0, a1
; NOSRL-NEXT:    jalr zero, 0(ra)
entry:
  %shr = lshr i32 %x, %y
  ret i32 %shr
}
